### ISSUE TITLE
Custom hash length

### ISSUE THREAD

**Issue by SAnDAnGE** [sindresorhus/gulp-rev#102]
Greetings, the last change increased the hash length from 8 to 10 without the option to keep the old version. I am working on a project that revs 800 files and I need to mark them as renamed and commit to the repository. Could you please add the option with default to 8/10 ?... whatever you want.

**Comment by sindresorhus** [comment]
Not interested in adding an option. This was a **major** version for a reason. Just stay at 1.0.0 then. Nothing new except for that.
