### ISSUE TITLE
Why vX.X.X for all others and 4.0.0 on tag?

### ISSUE THREAD

**Issue by kud** [sindresorhus/gulp-rev#105]

**Comment by kevva** [comment]
Because newest npm supports `tag-version-prefix`. Before when you ran `npm version <major|minor|patch>` it would create tags with a `v` prefixed. Now, when setting `tag-version-prefix=`, it doesn't anymore.

**Comment by kud** [comment]
Okay thank you. ;)

**Comment by kud** [comment]
https://github.com/kud/my/commit/1bc09c033921716465b557de9750732f646a7033

Thank you again @kevva. ;)
