### ISSUE TITLE
Provide an option to append the hash the the beginning of the filename

### ISSUE THREAD

**Issue by elisechant** [sindresorhus/gulp-rev#106]
It would be useful to choose for the hash to append to beginning of the filename instead of the suffix, like ``732527635-global.min.js`` instead of the current format which is ``global.min-732527635.js``

This pattern is a believed to be a best practice for CDNs because it disperses the collection of assets more randomly and avoids what's known as 'hotspots'.

**Comment by sindresorhus** [comment]
I prefer not to add any more options to this module. It currently covers the 95% use-case. If you need more there are other more feature-rich plugins available.

**Comment by elisechant** [comment]
ok then
