### ISSUE TITLE
Question: why not styles.css?timestamphere format ?

### ISSUE THREAD

**Issue by elnygren** [sindresorhus/gulp-rev#107]
`styles-timestamphere.css` -> I have to handle to rename the files AND rename the links to them

`styles.css?timestamphere` -> I only need to rename links (in index.html or header/footer partials or where ever I have my css/js)

Is this a browser support thing ?

**Comment by sindresorhus** [comment]
Some proxies and servers had problems with query strings so renaming became a best practise instead.

Google it ;)
