### ISSUE TITLE
Adding prefix /

### ISSUE THREAD

**Issue by newtonianb** [sindresorhus/gulp-rev#117]
All my paths in the manifest start with ``assets/file.js`` I would like them to be ``/assets/file.js``

How can I do this? I looked at base: but that didn't seem to work

**Comment by bobthecow** [comment]
why?

**Comment by tommymarshall** [comment]
@bobthecow because relative paths are the devil?

**Comment by newtonianb** [comment]
:) precisely,, I mean when would it ever be useful to be relative

**Comment by torifat** [comment]
@newtonianb closing this issue. You can easily achieve what you want in various ways. It doesn't feel like something "must have" for this plugin at this moment.
