### ISSUE TITLE
gulp-rev with gulp-flatten - flattening source path

### ISSUE THREAD

**Issue by mahnunchik** [sindresorhus/gulp-rev#118]
Behavior has been changed compared to the version 3 of gulp-rev.

package.json
```json
  "dependencies": {
    "gulp": "^3.9.0",
    "gulp-flatten": "^0.1.1",
    "gulp-load-plugins": "^0.10.0",
    "gulp-rev": "^5.1.0"
  }
```

Task
```js
gulp.task('default', function() {
  gulp.src('src/**/*')
    .pipe($.rev())
    .pipe($.flatten())
    .pipe(gulp.dest('dist'))
    .pipe($.rev.manifest())
    .pipe(gulp.dest('.'));
});
```

File structure of src folder:
```
src/
├── css
│   └── main.css
└── images
    └── image.png
```

Actual rev-manifest.json
```json
{
  "image.png": "image-1f7c46e5d7.png",
  "main.css": "main-3aab9a4367.css"
}
```
Source paths are flattened.

Expected rev-manifest.json
```json
{
  "images/image.png": "image-1f7c46e5d7.png",
  "css/main.css": "main-3aab9a4367.css"
}
```

As if we launch task without flattening.
```json
{
  "images/image.png": "images/image-1f7c46e5d7.png",
  "css/main.css": "css/main-a12addf639.css"
}
```

**Comment by mahnunchik** [comment]
Hi @sindresorhus 

If it is correct behavior then please document it.

**Comment by torifat** [comment]
@mahnunchik this is how it works now. Can you help us document it?

Please reopen the issue if you are interested in helping.  Because, it is difficult for us to document compatibility of various other plugins.
