### ISSUE TITLE
Rename the revised path

### ISSUE THREAD

**Issue by karellm** [sindresorhus/gulp-rev#119]
I have retina assets like `image@2x.png` and passing through `rev` I end up with `images@2x-123123123.png`.

It is obviously not what I want, I would expect `images-123123123@2x.png` (note where the `@2x is located). Is it something you have or could build? Right now it somewhat of a tedious process:

- task 1: rev
- task 2: revreplace with a custom method to change the path
- task 3: rename generated images

All this would be a LOT simpler if you offered a rename function the way [gulp-rev-replace](https://github.com/jamesknelson/gulp-rev-replace#optionsmodifyunreved-optionsmodifyreved) does it here.

Thanks!

**Comment by sindresorhus** [comment]
`@2x` is just a convention, but I guess we could support it. PR welcome.

**Comment by karellm** [comment]
@sindresorhus This issue I found is that your image and its retina version are still two different assets with different versions. So the hash will be different, and the automatic `@2x` only works if we file name is the same.

I think that optimization is more important than automation for me so I ended up manually pointing to my retina files. And then this is not a problem anymore.

If someone want to implement this, they need to group the image and its retina version and make sure that if one change, both version change. That will cause problem with the checksum.

Anyway, closing this for now. Feel free to reopen if someone wants to tackle it.
