### ISSUE TITLE
v6.0.0 works wrong

### ISSUE THREAD

**Issue by yoyurec** [sindresorhus/gulp-rev#122]
something gest wrong with new release (((
it doesn't do revision for all files
and for those who do - places to sibling folder of project with md5 folder name. 
crazy behavior :disappointed_relieved:

**Comment by sindresorhus** [comment]
Yeah, 6.0.0 has a severe bug: https://github.com/sindresorhus/gulp-rev/pull/121

Fixed in 6.0.1.

Though keep in mind that 6.0.0 now considers everything after the first dot the extension, not the last dot as it previously did.

**Comment by yoyurec** [comment]
> 6.0.0 now considers everything after the first dot the extension
so `app.deferred.js` will be `app.123456.deferred.js` not `app.deferred.123456.js`? (((

**Comment by sindresorhus** [comment]
Neither → `app-123456.deferred.js`
