### ISSUE TITLE
Merge: true not working for rev.manifest()

### ISSUE THREAD

**Issue by nsdiv** [sindresorhus/gulp-rev#123]
I use gulp-rev 4 times, once for js, css, templates and for the concatenated and minified JS. The merge option is set to true. However the manifests are not merged, but overwritten. How do I get the rev.manifest() to merge?
Note - I do understand that the gulp.dest() causes the file to be overwritten. But how else do you merge?
        
        // Include gulp
	var gulp = require('gulp'); 

	// Include Our Plugins
	var jshint = require('gulp-jshint');
	var sass = require('gulp-sass');
	var concat = require('gulp-concat');
	var uglify = require('gulp-uglify');
	var rename = require('gulp-rename');
	var rev = require('gulp-rev');
	var del = require('del');
	var confirm = require('gulp-confirm');

	//gulp runs tasks async, but that causes issues for us.

	gulp.task('clean', function () {
	    return del([
	        'dist/**/*' // clean out this directory
	    ]);
	});

	// Lint Task
	gulp.task('lint', ['clean'], function() {
		//return gulp.src('js/**/*.js')
		//    .pipe(jshint())
		//    .pipe(jshint.reporter('default'));
	    });

	// Compile Our Sass
	gulp.task('sass', ['lint'], function() {
		//return gulp.src('sass/*.scss')
		//    .pipe(sass())
		//    .pipe(gulp.dest('css'));
	    });

	gulp.task('rev-js', ['sass'], function () {
	    return gulp.src(['js/**/*.js'])
	        //.pipe(gulp.dest('dist/js')) // copy files to dist
	        .pipe(rev()) // revision them
	        .pipe(gulp.dest('dist/js')) // copy the revision files to dist
	        .pipe(rev.manifest("rev-manifest.json", {
	            merge: true // merge with the existing manifest (if one exists)
	        }))
	        .pipe(gulp.dest('dist'))
	        .pipe(confirm({
	            // Static text.
	            question: 'Completed rev JS. Continue?',
	            input: '_key:y'
	        }));
	});

	gulp.task('rev-css', ['rev-js'], function () {
	    return gulp.src(['css/*.css'])
	        //.pipe(gulp.dest('dist/css')) // copy files to dist
	        .pipe(rev()) // revision them
	        .pipe(gulp.dest('dist/css')) // copy the revision files to dist
	        .pipe(rev.manifest("rev-manifest.json", {
	            merge: true // merge with the existing manifest (if one exists)
	        }))
	        .pipe(gulp.dest('dist'))
	        .pipe(confirm({
	            // Static text.
	            question: 'Completed rev CSS. Continue?',
	            input: '_key:y'
	        }));
	});

	gulp.task('rev-templates', ['rev-css'], function () {
	    return gulp.src(['templates/**/*.html'])
	        //.pipe(gulp.dest('dist/templates')) // copy files to dist
	        .pipe(rev()) // revision them
	        .pipe(gulp.dest('dist/templates')) // copy the revision files to dist
	        .pipe(rev.manifest("rev-manifest.json", {
	            merge: true // merge with the existing manifest (if one exists)
	        }))
	        .pipe(gulp.dest('dist'));
	});

	// Concatenate & Minify JS
	gulp.task('scripts', ['rev-templates'], function() {
		gulp.src('js/**/*.js')
		    .pipe(concat('all.js'))
		    .pipe(gulp.dest('dist'))
		    .pipe(rename('all.min.js'))
		    .pipe(uglify())
	        .pipe(gulp.dest('dist'))
	        .pipe(rev())
		    .pipe(gulp.dest('dist'))
	        .pipe(rev.manifest("rev-manifest.json", {
	            merge: true // merge with the existing manifest (if one exists)
	        }))
	        .pipe(gulp.dest('dist'));
	    });

	// Watch Files For Changes
	gulp.task('watch', ['scripts'], function() {
		//gulp.watch('js/*.js', ['lint', 'scripts']);
		//gulp.watch('scss/*.scss', ['sass']);
	    });

	// Default Task
	gulp.task('default', ['watch']);

**Comment by goooseman** [comment]
I use
```
.pipe($.rev.manifest('dist/rev-manifest.json', {base: process.cwd()+'/dist', merge: true}))
.pipe(gulp.dest('dist'));
```

**Comment by c9dd** [comment]
I'm having the same issue that merge is overwriting the file

**Comment by mlarcher** [comment]
Indeed the merging feature doesn't appear to be working. Maybe I'm missing something, but it seems that the option isn't handled anywhere in the source code...

**Comment by bobthecow** [comment]
Merging is handled [right here](https://github.com/sindresorhus/gulp-rev/blob/master/index.js#L159-L167).

Everyone with this issue: your problem is likely that gulp tasks run in parallel (and async), and later tasks are overwriting earlier ones without merging their changes together. See #115 for a couple of things to try to fix your task definitions.

**Comment by mlarcher** [comment]
Sorry, I was looking at gulp-rev-replace instead of gulp-rev source code. Apologies.

**Comment by mlarcher** [comment]
Anyhow, I tried various methods and can't get the rev-manifest.json file to get preserved.
Here's my current setup making use of run-sequence to ensure tasks don't run in parallel. It does everything I want, but only the main js/css files end up in the manifest.
```
"use strict";

var gulp = require('gulp');
var rev = require('gulp-rev');
var path = require('path');
var revReplace = require("gulp-rev-replace");
var gutil = require('gulp-util');
var runSequence = require('run-sequence');

var handleErrors = require('../utils/handle-errors');
var config = require('../config/config');


gulp.task("rev-assets", function () {
  return gulp.src([
    path.join(config.dest, '/**/fonts/**/*'),
    path.join(config.dest, '/**/css/img/**/*'),
    path.join(config.dest, '/**/img/**/*')
  ])
    .pipe(rev())
    .pipe(gulp.dest(config.dest))
    .pipe(rev.manifest())
    .pipe(gulp.dest(config.dest))
});

gulp.task("rev-replace", /*["rev-assets"],*/ function () {
  var manifest = gulp.src(config.dest + "/rev-manifest.json");

  return gulp.src(path.join(config.dest, '/**/*.{css,html}'))
    .pipe(revReplace({manifest: manifest}))
    .pipe(gulp.dest(config.dest));
});

gulp.task("rev-main", /*['rev-replace'],*/ function () {
  return gulp.src([
    path.join(config.dest, '/**/*.css'),
    path.join(config.dest, '/**/*.js')
  ])
    .pipe(rev())
    .pipe(gulp.dest(config.dest))
    .pipe(rev.manifest({
      merge: true
    }))
    .pipe(gulp.dest(config.dest))
});

gulp.task("rev", function(done) {
  runSequence('rev-assets', 'rev-replace', 'rev-main',
    done);
});
```
Could you by any chance provide a working recipe for revisionning static assets, referencing them with their hash in some files (html, css..), then revisionning those (html/css) files (their content might have changed only by the fact that some references were replaced) ?

**Comment by joezimjs** [comment]
Yea, it's definitely not working.

**Comment by wk1017553772** [comment]
I agree with @goooseman ,
```javascript
.pipe(rev.manifest('dist/rev-manifest.json', {base: process.cwd()+'/dist', merge: true}))
.pipe(gulp.dest('dist'));
```
it working!!

**Comment by LoicUV** [comment]
You indeed **HAVE** to pass the path of the manifest as parameter before the options if you want the merge to work, here is the example corrected : 
```javascript
var gulp = require('gulp');
var rev = require('gulp-rev');

gulp.task('default', function () {
    // by default, gulp would pick `assets/css` as the base,
    // so we need to set it explicitly:
    return gulp.src(['assets/css/*.css', 'assets/js/*.js'], {base: 'assets'})
        .pipe(gulp.dest('build/assets'))
        .pipe(rev())
        .pipe(gulp.dest('build/assets'))
        .pipe(rev.manifest('build/assets/rev-manifest.json', {
            base: 'build/assets',
            merge: true // merge with the existing manifest (if one exists)
        }))
        .pipe(gulp.dest('build/assets'));
});
```

**Comment by bensampaio** [comment]
I'm having this exact same problem and none of the suggestions are working for me. I'm even using `gulp-sync` to make sure there are no parallel tasks writing to the manifest file... I can see the manifest file being changed after each tasks finishes. Everyone of my tasks ends like this:

```js
.pipe(rev())
.pipe(gulp.dest(destFolder))
.pipe(rev.manifest('rev-manifest.json', { merge: true }))
.pipe(gulp.dest(buildFolder))
```

Any suggestions?

**Comment by bobthecow** [comment]
@bensampaio you need to supply a base for your `rev.manifest` call:

```js
.pipe(rev.manifest('rev-manifest.json', { merge: true, base: buildFolder }))
```

**Comment by bobthecow** [comment]
Everyone with this issue: `rev.manifest` _can't tell where your existing file is_ if you're writing it to another directory via `gulp.dest`. It doesn't know the future, it doesn't know that one line later in your code you're going to be redirecting it to another folder. It has no idea where to look unless you tell it. So pass a `base` option if you're writing your manifest somewhere else via `gulp.dest` :)

**Comment by bensampaio** [comment]
I don't get it... It just doesn't work for me... I currently have the following:

```js
let destFolder = '/absolute/path/to/dist';
let buildFolder = '/absolute/path/to/build';

gulp.src('/absolute/path/to/some/file')
  .pipe(rev())
  .pipe(gulp.dest(destFolder))
  .pipe(rev.manifest('rev-manifest.json', { merge: true, base: buildFolder }))
  .pipe(gulp.dest(buildFolder))
```

The manifest file always ends up being written to `process.cwd()` instead of the folder where I want it to be... Besides that, it is never merged... Is there any problem if the paths are absolute? Should I have some different configuration because of that?

**Comment by LoicUV** [comment]
@bensampaio try to change the path of the rev-manifest in this line :
`.pipe(rev.manifest('rev-manifest.json', { merge: true, base: buildFolder }))`
to the same as the base path : 
`.pipe(rev.manifest(buildFolder + '/rev-manifest.json', { merge: true, base: buildFolder }))`

**Comment by bensampaio** [comment]
Ok that worked! Thanks! However, I still have problems with merging. If I create one single task that uses `rev()` on all files I need then it works. However, if I have multiple tasks using `rev()` and even if I use `gulp-sync` to make sure they are not run in parallel, my manifest file will contain only the results from the last executed task...

**Comment by Altareq** [comment]
here is what i do that works fine for me, i have few tasks running in sequence, sorting them is important, otherwise if order is not important, you could run them in parallel and have `gulp-rev-collector` to collect them all. yet as the need is sequence that is what i did that works. basically, your first task that creates the manifest `must` have an option `{merge: true}`, otherwise any subsequent tasks wont really work for you, even if you specify the `base` build folder and `merge` options.

here is some code that might help

first, is a sequence task that needs to run few things
```
var config = require('../../config'); // my configuration file that holds all variables
var gulp = require('gulp');
var gulpSequence = require('gulp-sequence');

// add versions to all compiled assets other than css/js
// then replace image url references in compiled css files
// then add versions to js and css files
gulp.task('rev', function(cb) {
  var tasks = ['rev-image-assets', 'replace-css-image-urls', 'rev-js-css-assets'];
  tasks.push(cb);
  gulpSequence.apply(this, tasks);
});
```
the third tasks `rev-js-css-assets` above which actually needs to merge in previous manifest created in `rev-image-assets` looks like this, notice that you can also reference your js/css together like this `gulp.src(config.publicAssets + '/**/**.{js,css}')`

```
var config = require('../../config');
var gulp   = require('gulp');
var rev    = require('gulp-rev');

// Add md5 hashes to js,css assets
gulp.task('rev-js-css-assets', function(){
  return gulp.src(config.publicAssets + '/**/**.{js,css}')
    .pipe(rev())
    .pipe(gulp.dest(config.publicAssets))
    .pipe(rev.manifest(config.manifest, { base: config.publicAssets, merge: true }))
    .pipe(gulp.dest(config.manifestPath));
});
```
my first task is a normal one and the rev manifest pipe looks like this

`.pipe(rev.manifest({merge: true}))` // notice here merge is true, if you remove that, no other references can be merged anymore, neither they get overridden, as you are not really preparing the manifest to be merge-able

Hope it might help.

**Comment by OliverJAsh** [comment]
`vinyl-file` doesn't pick up the `base` option we pass into it: https://github.com/sindresorhus/vinyl-file/blob/9bdbc6d9211d7d896e2e3c88afa8beb530d873b7/index.js#L19

Is that a bug in `vinyl-file`?

If I pass in a `cwd` option instead of `base`, it works:

```
.pipe(rev.manifest({
    cwd: './public',
    merge: true
}))
```

**Comment by kiddo13** [comment]
I also bumped to this problem.
To solve it, first I dump each files to different manifest json file. (Ex: a.json, b.json and etc).
After all tasks (which has its own manifest file) finished, I use a task to merge all that files into 1 manifest file. Here is the example code:

``
gulp.task('css', function() {
  gulp.src(['css/**/*.css'])
    .pipe(concat())
    .pipe(rev())
    .pipe(gulp.dest('dist/css'))
    .pipe(rev.manifest('tmp/manifest/css-manifest.json'))
    .pipe(gulp.dest('.'));

gulp.task('js', function() {
  gulp.src(['js/**/*.js'])
    .pipe(concat())
    .pipe(rev())
    .pipe(gulp.dest('dist/js'))
    .pipe(rev.manifest('tmp/manifest/js-manifest.json'))
    .pipe(gulp.dest('.'));
});

gulp.task('manifest', function() {
  gulp.src(['tmp/manifest/*.json'])
    .pipe(extend('rev-manifest.json'))
    .pipe(gulp.dest('.');
});

gulp.task('build', ['css', 'js']);

// Run the task synchronously
gulp.task('default', shell.task([
  'gulp build',
  'gulp manifest'
]);
``

Currently this method works for me. But I don't know wether this is a good way.
Any suggestion is really appreciated.

**Comment by codepodu** [comment]
@OliverJAsh I just spent 30 mins investigating the same issue, and found the same thing. I just changed `base: 'dist'` to `cwd: 'dist'` and everything started working. I'll send a PR to change the docs.

**Comment by gammaSharma** [comment]
Hi all,

Was stuck with the same problem of async task overwriting each other's entries in the rev-manifest.json file. I needed to rev up four files 

1. vendor-bundle.min.js
2. vendor-bundle.min.css
3. app.min.js
4. app.min.css

SOLn:
`.pipe(rev.manifest(DIST_PATH + '/hashed/rev-manifest.json', { merge: true, base: DIST_PATH + '/hashed' }))`

Providing the {base} option is mandatory, and the same path, PLUS the menifest name at the same time too.

**Comment by iMuFeng** [comment]
@codepodu it works now, tks

**Comment by phillipcavaco** [comment]
My `rev-manifest.json` isn't merging properly. Only one file is mapped when using concurrent tasks.
But when I comment the concat line it does map all tasks.
I already tried several of the above solutions by forcing path and name and none worked out.

gulp-rev 7.0.0


```javascript
// my gulpfile.js
var gulp = require('gulp');
var jshint = require('gulp-jshint');
var uglify = require('gulp-uglify');
var concat = require('gulp-concat');
var rev = require('gulp-rev');

var jsFiles = {
	task1: [
		'./path/file1.js'
	],
	task2: [
		'./path/file2.js',
    	'./path/file2.js'
	]
};


function jsTask(key) {
	gulp.task(key, function() {
		gulp.src(jsFiles[key])
			.pipe(jshint())
			.pipe(jshint.reporter('default'))
			.pipe(uglify())
			// IT WORKS WHEN I COMMENT THIS LINE
			.pipe(concat(key + '.min.js'))
			.pipe(rev())
			.pipe(gulp.dest('./public/js'))
			.pipe(rev.manifest({merge:true }))
        	.pipe(gulp.dest('.'));
	});
}



for (var key in jsFiles) {
	jsTask(key);
}


var defaultTasks = [];
for (var key in jsFiles) {
	defaultTasks.push(key);
}

gulp.task('default', defaultTasks);
```

**Comment by mtpultz** [comment]
@LoicUV I've followed what you suggested, but it still doesn't seem to merge:

```
gulp.task('revision-scripts', [], function () {

    helpers.log('Revision Scripts');

    var source = [
        path.join(
            config.publicPath,
            config.js.outputFolder,
            config.js.outputFile
        )
    ];

    var manifestFile = 'build/rev-manifest.json';

    var manifestOptions = {
        base: 'build/js',
        merge: true // merge with the existing manifest (if one exists)
    };

    var outputFolder = path.join(
        config.publicPath,
        'build/js'
    );

    return gulp.src(source, {base: 'public/build'})
               .pipe(plumber())
               .pipe(rev())
               .pipe(gulp.dest(outputFolder))
               .pipe(rev.manifest(manifestFile, manifestOptions))
               .pipe(gulp.dest(outputFolder));
});
```

```
gulp.task('revision-styles', [], function () {

    helpers.log('Revision Styles');

    var source = [
        path.join(
            config.publicPath,
            config.css.outputFolder,
            config.css.outputFile
        )
    ];

    var manifestFile = 'build/rev-manifest.json';

    var manifestOptions = {
        base: 'build/css',
        merge: true // merge with the existing manifest (if one exists)
    };

    var outputFolder = path.join(
        config.publicPath,
        'build/css'
    );

    return gulp.src(source, {base: 'public/build'})
               .pipe(plumber())
               .pipe(rev())
               .pipe(gulp.dest(outputFolder))
               .pipe(rev.manifest(manifestFile ,manifestOptions))
               .pipe(gulp.dest(outputFolder));
});
```

I have revision-scripts and revision-styles (almost identical except for the files being revisioned), but if I call revision-scripts after revision styles in the terminal (or vice versa) they overwrite the manifest, and the files aren't prefixed with /js or /css in the manifest keys:

**Run:** `gulp revision-scripts`
```
{
  "app.js": "app-cf4ghahu8e.js"
}
```

**Run:** `gulp revision-styles`
```
{
  "app.css": "app-aee90af68e.css"
}
```

**Folder Structure**
```
/build
    rev-manifest.json
    /js
        app-cf4ghahu8e.js
        app.map.js
    /css
        app-aee90af68e.css
        app.map.css
```

**Comment by LoicUV** [comment]
@mtpultz if I'm not mistaken, according to your folder structure, the last line in both of your tasks is wrong:
```
    .pipe(gulp.dest(outputFolder));
```
It outputs two `rev-manifest.json`, one to `build/css/` & one to `build/js` instead of just one in `build/`.
Your base path is also wrong in manifest options:
```
    var manifestOptions = {
        base: 'build/css',
        merge: true // merge with the existing manifest (if one exists)
    };
```
Should be `base: 'build',` for both your tasks.

Aside from that, if this still doesn't work, I got it working somehow by calling `rev.manifest()` without parameters in my first task (css), and in my second task (js, adjusted with your folder settings):
```
var folder = path.join(
    config.publicPath,
    'build/'
);
rev.manifest(folder + 'rev-manifest.json', {
    base: folder,
    merge: true
})
```

**Comment by mtpultz** [comment]
Hi @LoicUV, sorry I ended up updated my issue above before seeing your response after playing more with it.  I believe it makes the changes you suggested.  It provides the folder structure I need with a single manifest file, but the manifest still gets overwritten.  Wouldn't that mean both CSS and JS revisions would have to run if you changed just the JS?

**Comment by LoicUV** [comment]
No it will only change the revision if the code has changed, otherwise it will keep the same one. As for the output, it doesn't include the folder structure in it. I have the same build structure as you and my manifest contains `"main.css": "main-3f3b917b49.css"` and not `"css/main.css": "main-3f3b917b49.css".

**Comment by lukeed** [comment]
@mtpultz @LoicUV Because you've set the `gulp.src {base}` property, the plugin is looking for an existing manifest file inside `public/` and **not** `public/build`.

You may try:

1) Changing the `base` value on your `gulp.src` to `outputFolder`
2) Adding in a `{path: 'public/build/rev-manifest.json'}` option along with your `merge`

As seen [in the code](https://github.com/sindresorhus/gulp-rev/blob/master/index.js#L26), the plugin looks for a manifest solely based on `opts.path`. If one is not found, then `merge: true` becomes irrelevant.

**Comment by LoicUV** [comment]
Oh right, I don't use `gulp.src {base}` so that explains it.

**Comment by lukeed** [comment]
Me neither. Pretty sure I inadvertently found more problems with it than solutions 😉

**Comment by lukeed** [comment]
@mtpultz You may also try the `base` option, as mentioned [here](https://github.com/sindresorhus/gulp-rev/issues/123#issuecomment-158779118).

Closing this issue as it's quite old & become difficult to follow, which obscures the solutions that have already been provided.

**Comment by omarabid** [comment]
@ LoicUV The solution provided did work.  I think the documentation needs to be updated.
