### ISSUE TITLE
Add time stamp to rev hash ...

### ISSUE THREAD

**Issue by michalskyPL** [sindresorhus/gulp-rev#127]
Hi, my gulp-rev add revs to zipped app/page template.

my workflow app -> zip -> revision, and i want to add a timestamp to rev hash like this : date_hash_filename.ext

my gulpfile.js

var rev = require('gulp-rev');
var date = new Date(dateString);
gulp.task('rev', function () {
  return gulp.src('app/*.zip')
    .pipe(rev())
    .pipe(gulp.dest('deploy/'));
});

Should i add new Date().toString()) to rev() or edit the index.js in rev-hash or rev-path ?

**Comment by kevva** [comment]
https://github.com/sindresorhus/gulp-rev#asset-hash
