### ISSUE TITLE
Question: Adding Version instead of Content File Hash at the end?

### ISSUE THREAD

**Issue by akshayKrSingh** [sindresorhus/gulp-rev#129]
As a feature, would it not be cool to have an option to use `package.json` **version** tag value to be suffixed at the end of file name rather than using content hash?

##### `mode: 'version'`
```Javascript
var gulp = require('gulp');
var rev = require('gulp-rev');

gulp.task('default', function () {
    return gulp.src('src/*.css')
        .pipe(rev({mode: 'version'}))
        .pipe(gulp.dest('dist'));
});
```
##### Output
`abc-1.2.0.css`

##### Default or None
```Javascript
var gulp = require('gulp');
var rev = require('gulp-rev');

gulp.task('default', function () {
    return gulp.src('src/*.css')
        .pipe(rev() /* or rev({mode: 'default'})*/)
        .pipe(gulp.dest('dist'));
});
```
##### Output
`abc-bxc23dd564c.css`

**Comment by sindresorhus** [comment]
Sounds like a really bad idea. That would invalidate the cache for all files even though only some changed.

**Comment by akshayKrSingh** [comment]
Agreed, but for cases where the plugin is being used to generate semver builds, for e.g. jQuery-1.2.3.js etc ... this can come in handy. Also, It can only be an option.

**Comment by kevva** [comment]
I don't think this plugin should be used to generate semver builds though.

**Comment by bobthecow** [comment]
gulp-rename is a perfect plugin for the job :)

**Comment by akshayKrSingh** [comment]
@bobthecow : Thanks, how did I miss that :( !!

**Comment by bobthecow** [comment]
@akshayKrSingh Heh. No worries :)
