### ISSUE TITLE
Doesnt work with zip

### ISSUE THREAD

**Issue by Petah** [sindresorhus/gulp-rev#130]
I tried making the work with a packaged zip file but it give a new hash every time I run it even though nothing has changed:

```
gulp.task('package', function () {
    gulp.src([
            'classes/**/*.*',
            'vendor/**/*.*',
            'public/**/*.*',
            'views/**/*.*',
        ], {
            base: '.',
        })
        .pipe(zip('package.zip'))
        .pipe(rev())
        .pipe(gulp.dest('packages'));
});
```

**Comment by kevva** [comment]
It's most likely due to the zip having a different hash every time it's packaged.

**Comment by sindresorhus** [comment]
You [can't use ZIP](http://stackoverflow.com/questions/9714139/why-does-zipping-the-same-content-twice-gives-two-files-with-different-sha1) to get a deterministic output. Use tar instead with this package: https://github.com/dominictarr/deterministic-tar
