### ISSUE TITLE
Revision only file name not extention

### ISSUE THREAD

**Issue by HamsterCoder** [sindresorhus/gulp-rev#132]
I have a manifest.json that looks very strange in my opinion:
```
{
  "app.css": "app-daaba8d210.css",
  "app.js": "app-db6dbc5a16.js",
  "app.js.map": "app.js-80c08d78c3.map"
}
```

I would expect the last revision to looks something like app-80c08d78c3.js.map

Also when using **gulp-rev-replace** plugin with this manifest I get this result which points nowhere:

```
//# sourceMappingURL=app-db6dbc5a16.js-80c08d78c3.map
```

Evidently replaced many times - instead of once. Maybe this source map situation is ambigues by default.

Is it intended behaviour or a bug, is there any known workaround?

**Comment by torifat** [comment]
It should work. Check: https://github.com/sindresorhus/gulp-rev/blob/master/test.js#L22-L37

Can you share your `gulp` task or add a test case? So, that I can reproduce it and fix it.

**Comment by HamsterCoder** [comment]
*  tasks
```
var revision = require('gulp-rev');
var revisionReplace = require('gulp-rev-replace');

gulp.task('revision', function () {
        return gulp.src(filesWithRevision.map(function (filename) {
            return DIST + filename;
        }))
            .pipe(revision())
            .pipe(gulp.dest(DIST))
            .pipe(revision.manifest())
            .pipe(gulp.dest(DIST));
    });

    gulp.task('revisionreplace', ['revision'], function () {
        var readableManifest = require(DIST + 'rev-manifest.json');
        var manifest = gulp.src(DIST + 'rev-manifest.json');
        var filesWithReplacedRevision = [DIST + 'index.html'];

        filesWithReplacedRevision.push(DIST + readableManifest['app.js']); // To replace sourcemap revision

        return gulp.src(filesWithReplacedRevision)
            .pipe(revisionReplace({ manifest: manifest }))
            .pipe(gulp.dest(DIST));
    });
```

  *  versions

```
  "gulp-rev": "^5.1.0",
  "gulp-rev-replace": "^0.4.2",
```

  *  filesWithReplacedRevision

```
[ './dist/index.html', './dist/app-db6dbc5a16.js' ]
```

I am testing on Windows 7 with Git Bash and on Ubuntu 12.04.4 LTS

I also saw something similar in this closed issue #85 - see `main.ie.css`

**Comment by torifat** [comment]
@HamsterCoder Please update `gulp-rev`. `5.1.0` is the reason you are getting this.

**Comment by HamsterCoder** [comment]
Thanks a lot guys =)
