### ISSUE TITLE
gulp-qn

### ISSUE THREAD

**Issue by zhangda89** [sindresorhus/gulp-rev#133]
i have some question when i use gulp-qn,
i want below
```
{
  "styles.css": "http://7sbph3.com1.z0.glb.clouddn.com/css/styles-46ac99d6b4.css"
}
```
but i get
```
{
  "http://7sbph3.com1.z0.glb.clouddn.com/css/styles.css": "http://7sbph3.com1.z0.glb.clouddn.com/css/styles-46ac99d6b4.css"
}
```
i change
```
var originalFile = path.join(path.dirname(revisionedFile), path.basename(file.revOrigPath)).replace(/\\/g, '/');
```

to
```
var originalFile = path.join(path.basename(file.revOrigPath)).replace(/\\/g, '/');
```
i get correct result.why?

**Comment by torifat** [comment]
Sorry, `gulp-qn` has no documentation. It is dificult to test aginst random plugins with no documentation.

You get correct result because you are removing `path.dirname('http://7sbph3.com1.z0.glb.clouddn.com/css/styles.css')` which is `http://7sbph3.com1.z0.glb.clouddn.com/css)`
