### ISSUE TITLE
How should source maps be handled?

### ISSUE THREAD

**Issue by OliverJAsh** [sindresorhus/gulp-rev#137]
Does this project support `gulp-sourcemaps`? https://github.com/floridoo/gulp-sourcemaps

I have a stream that emits two files: a JS file and the corresponding source map.

If I use gulp-rev, both of these files will be revisioned, i.e. `foo-1.js` and `foo-2.js.map`. This will prevent the source map from being loaded, as browsers will automatically request source map files by appending `.map` to the end of the filename. In this case, `foo-1.js.map` will not be found.

What is the correct behaviour here? Should gulp-rev update the `sourceMappingUrl` with the revisioned source map filename? Or, should the source map have the same revision file name as the original file, i.e. `foo-1.js` and `foo-1.js.map`?

**Comment by torifat** [comment]
@OliverJAsh can you please share the task?

**Comment by sindresorhus** [comment]
> I have a stream that emits two files: a JS file and the corresponding source map.

That's not how `gulp-sourcemaps` works. It adds the sourcemap as a property to the `file` object. This plugin supports that: https://github.com/sindresorhus/gulp-rev/blob/master/index.js#L88
