### ISSUE TITLE
 unicorn.css → unicorn.css?v20151125

### ISSUE THREAD

**Issue by yuanzx** [sindresorhus/gulp-rev#138]
is there a option to append timespan not md5 to the filename like this unicorn.css → unicorn.css?v20151125,not unicorn-43dsdsds.css?

**Comment by torifat** [comment]
@yuanzx no. But, why do you even need time instead of hash?

**Comment by yuanzx** [comment]
@torifat I think  the filename with time  is easy to know when the it is changed

**Comment by torifat** [comment]
@yuanzx you can just check it's creation time.
