### ISSUE TITLE
Make common base logic optional

### ISSUE THREAD

**Issue by jkrems** [sindresorhus/gulp-rev#140]
Hi!

As part of the build process, we move all our assets into one common directory. Which means that for us base directory differences are meaningless. With the current logic in `gulp-rev`, we have to resort to ugly hacks or we end up with invalid paths in our manifest file. Would you accept a PR that makes the `firstFile` magic optional and introduces an opt-in option that always uses the `base` of the current file when determining the manifest key?

**Comment by Tanato** [comment]
I had the same issue and reported it duplicated in #141 and fix it in PR #142.

Hope they accept my PR, this issue is making my gulpfile such a mess.

**Comment by hsablonniere** [comment]
Hey, we have exactly the same issue. Without this PR, we need write a lot of lines in our Gulpfile :-(

**Comment by hsablonniere** [comment]
:heart:
