### ISSUE TITLE
How to rev without index.html

### ISSUE THREAD

**Issue by gembin** [sindresorhus/gulp-rev#146]
How to rev without index.html ?
Currently my index.html is renamed

**Comment by torifat** [comment]
Sorry, didn't understand your problem. Check the *Usage* section, it doesn't need any index.html to work.

**Comment by gembin** [comment]
Sorry!  Here is an example shows what i did.

```javascript
  
 gulp.task('build', function () {
  //....
  return gulp.src(path.join(conf.paths.tmp, '/serve/index.html'))
        .pipe($.useref({}, lazypipe().pipe($.sourcemaps.init, { loadMaps: true })))
        .pipe($.rev())
        // ... minify css
        // ... minify  js 
       // .. minify html
       .pipe(gulp.dest('build'))
});
```
And the index.html just get renamed to something like `index-d3cdb828b3.html`

**Comment by torifat** [comment]
@gembin you are not using it correctly. I've found a blog post which might help you - http://bendetat.com/cleaning-and-simplifying-the-gulp-pipeline.html

**Comment by gembin** [comment]
Thanks a lot, I will try it.

**Comment by torifat** [comment]
@gembin I just updated `useref` of our build today and faced the same problem. I solved it with-

```js
.pipe(gulpIf('!*.html', rev()))
```

I hope it will help.

**Comment by gembin** [comment]
Awesome, it works !

BTW:  is it possible to provide an option to use custom hash function?
e.g. i want `app.js` renamed like `app-v1.0.0.js`

**Comment by torifat** [comment]
@gembin I don't think so. It doesn't go with the main goal of our plugin.

**Comment by wembernard** [comment]
Thanks @torifat for the tip.

`.pipe(gulpIf('!*.html', rev()))`

Might be useful for many people to add this tip in the documentation, don't you think?
