### ISSUE TITLE
Usage of file.revOrigPath option

### ISSUE THREAD

**Issue by kozlitinaelja** [sindresorhus/gulp-rev#156]
Can you, please, provide how to use file.revOrigPath? I think it may be useful for me but I can't figure out how to enable it.

**Comment by benbieler** [comment]
Hello @kozlitinaelja.
The `file.revOrigPath` option ist indeed very usefull ;)
Basically you get the `file` from a callback function. On this you then can use the  `revOrigPath` option.       

#### Usage example:

```js
var through = require('through2');

var foo = function () {
  return through.obj(function(file, enc, cb) {
      // Here you can use: file.revOrigPath
  };
}
```

I hope this helps...
