### ISSUE TITLE
Maintainer needed

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/gulp-rev#158]
I don't have the time to maintain this project anymore. There's a lot of users, so would be nice if someone stepped up as an active maintainer. If no one steps up, I'll eventually deprecate this plugin as I'm not doing users any favor of having it go unmaintained.

**Comment by tjsail33** [comment]
I'm happy to step up. I've used gulp-rev in many projects and would be more than happy to take over the maintenance of the project

**Comment by rajzshkr** [comment]
I'm happy to join hands with @tjsail33  in maintaining this project.

**Comment by benbieler** [comment]
I would also love to be a maintainer for this project.

**Comment by sindresorhus** [comment]
Awesome! Added you all :)

The guidelines are simple. Be kind to everyone. Larger changes should come in a pull request. Smaller ones can be committed directly. Pull requests should have at least one :+1: from another maintainer before being merged (If there are more than one maintainer excluding me). Follow the existing [code style](https://github.com/sindresorhus/xo) (Tip: `$ xo --fix` can fix many issues) and ensure `npm test` passes before pushing a commit. You can use branches in this repo, but clean them up afterwards. I like a clean commit history, so when merging a pull request, either ask the contributor to [squash](http://stackoverflow.com/questions/11396069/squash-to-only-one-proper-commit-for-github-pull-request) their commits or do it for them manually.

Also keep in mind that the goal of this project is simplicity. That means solving a problem for the 90% with the least amount of options.

The next step would be to resolve the open pull requests. The documentation could also be improved.

**Comment by bobthecow** [comment]
:+1: Please please please be as aggressive at keeping this simple as @sindresorhus has been :)

**Comment by ajaybc** [comment]
@sindresorhus Very much interested in being a maintainer. After all have been using this in our project for the last 6 months  :smile:

**Comment by lukeed** [comment]
I'll help maintain this. I maintain [fly-rev](https://github.com/lukeed/fly-rev) anyways :+1:

**Comment by samarpanda** [comment]
I will be happy to maintain this project.

**Comment by sindresorhus** [comment]
@ajaybc @lukeed @samarpanda Thanks all. ❤️ Added.

**Comment by sindresorhus** [comment]
> Please please please be as aggressive at keeping this simple

That means adding new options is the last resort. Instead, use good defaults and try to solve the 90% use-case.

Adding options is a slippery slope. We don't want to end up with this:

![horrible-ui](https://cloud.githubusercontent.com/assets/170270/14455767/72c590ba-00cb-11e6-85d2-9a716286db96.png)

Great products is the result of saying 'no' to almost everything.

**Comment by tarungarg546** [comment]
@sindresorhus I'll be happy to be a small maintainer of this project.

**Comment by sindresorhus** [comment]
@tarungarg546 Do a pull request with some kind of bug fix or improvement and I'll add you ;)

**Comment by tarungarg546** [comment]
@sindresorhus Smart boy :lollipop:

**Comment by benbieler** [comment]
@sindresorhus Should this be kept open? Or can this be closed?

**Comment by sindresorhus** [comment]
I'm still looking for a maintainer that have the time and energy to move this plugin forward. For example, there hasn't been a real code change since last year.

**Comment by benbieler** [comment]
OK
