### ISSUE TITLE
Give option to choose where hash is inserted in filename

### ISSUE THREAD

**Issue by wongterrencew** [sindresorhus/gulp-rev#168]
Currently the hash is prepended before the first dot character.

Ex.
```
foo.bar.baz -> foo-0123456789.bar.baz
```

I'd like an option that allows the hash to be prepended before the final dot character.

Ex.
```
foo.bar.baz -> foo.bar-0123456789.baz
```

This is useful if you're using dots in the file name that are not related to any extensions whatsoever. I'd like to add an option hash parameter to `rev` maybe `rev({lastDot: true})`

**Comment by lukeed** [comment]
See solution within #169
