### ISSUE TITLE
Add mention bot

### ISSUE THREAD

**Issue by benbieler** [sindresorhus/gulp-rev#171]
### Description

https://github.com/facebook/mention-bot

#### Current issue
All the reviewers have to be mannually entered:
![bildschirmfoto vom 2016-04-30 22 25 51](https://cloud.githubusercontent.com/assets/10898370/14938411/bffb6bf6-0f22-11e6-95d9-4a656d23e831.png)

@sindresorhus This would be something that you would have to do, since you are the owner.

**Comment by sindresorhus** [comment]
Done
