### ISSUE TITLE
Add some contributing tools

### ISSUE THREAD

**Issue by benbieler** [sindresorhus/gulp-rev#174]
### Description

A gitter chat for this npm package would be quite cool! CodeClimate would be cool as well. Waffle.io would be good for issue management.

:+1: or :-1: ?

**Comment by benbieler** [comment]
@sindresorhus Whats your take? This would be something that (again) ;) you would have to do, since you are the owner, and can access the repo settings

**Comment by samarpanda** [comment]
Good have these features 👍

**Comment by sindresorhus** [comment]
I don't see the point of CodeClimate and Waffle. There are not that many issues. I'm happy to add Gitter.

**Comment by sindresorhus** [comment]
Gitter added.

To clarify re CodeClimate, we already run ESLint in Travis, so not much benefit.

**Comment by benbieler** [comment]
Ok, thanks!
