### ISSUE TITLE
Refactor tests

### ISSUE THREAD

**Issue by benbieler** [sindresorhus/gulp-rev#176]
### Description

Currently the [tests.js](https://github.com/sindresorhus/gulp-rev/blob/master/test.js) file is IHMO way to long (373 lines)... This should be split up.

What about using a nother testing framework e.g. mocha + chai?

**Comment by benbieler** [comment]
@sindresorhus whats your take?

**Comment by lukeed** [comment]
The length of the tests file is pretty much irrelevant. Given the fact that this is a node utility (and that it's a Sindre™ package), AVA should be the would-be test framework.

**Comment by kevva** [comment]
Yup, converting to `ava` would be highly appreciated.

**Comment by sindresorhus** [comment]
What @kevva said.
