### ISSUE TITLE
Why same md5 file has different hash version? 

### ISSUE THREAD

**Issue by xfight0** [sindresorhus/gulp-rev#178]
Hello developers, 
I deploy my app in different two host, and gulp generate two app.js file, but the same two js file generate  different hash version....
However the same two css file generate same hash version.
Why was that?

**Comment by sindresorhus** [comment]
That might be the case if those two hosts have different Node.js versions, as there was a change in the Buffer implementation at some point.

Might also be a case of https://github.com/sindresorhus/gulp-rev/issues/147.

**Comment by xfight0** [comment]
@sindresorhus Thank you
