### ISSUE TITLE
Add support for hash suffixes and prefixes

### ISSUE THREAD

**Issue by atamas101** [sindresorhus/gulp-rev#181]
### Add support for hash suffixes and prefixes

Because of backend needs I need some more control over resulted named of revved files, ex:

unicorn.css => unicorn-pre.d41d8cd98f.sfx.css

For me it wouldn't make sense to do it outside of this gulp-rev task so I forked it and will do a pull request soon.

**Comment by lukeed** [comment]
You can construct your output filenames yourself; more specifically, you can choose how & where to insert your file hash.

Please look at my answer in #169 for an example. Thanks ~

**Comment by atamas101** [comment]
@lukeed Thanks for the super quick response and for very helpful the hint to #169 .
While I understand and respect the reasons why you closed this, and reasons for wanting to keep the plugin simple, I think that allowing basic 'formatting' (such as custom prefixes or suffixes) to the hash that this plugin is appending, would be something that is part of the same "transformFilename" step, and should not require a new step through custom 'middleware' which involves reprocessing that filenames one more time.
Thank you again for the great work you guys do with this anyway.
In case you reconsider, I'd be happy to update the readme.md and do any ammends to my commit linked above. Otherwise, would you mind me publishing my fork as a separate NPM package?
Regards,

**Comment by lukeed** [comment]
@atamas101 No problem. 

The plugin's only job is create a `revHash` and preserve the original `revOrigPath`, while exposing an optional `base` for the path name "calculations". (There have been talks about moving _all_ the manifest-related functionality to its own plugin.)

With those two file values, you can do **anything you want**. And if you want to package up your custom functionality, it's certainly & easily doable.

In the example I provided, the only new dependency was `modify-filename`, but it's certainly not necessary. Here's another implementation, without that dependency, that will do exactly what you described in this issue:

```js
var gulp = require('gulp');
var rev = require('gulp-rev');
var through = require('through2');

gulp.task('version', function () {
  return gulp.src('src/test.js')
    .pipe(rev())
    .pipe(through.obj(function (file, enc, cb) {
      console.log(file.revOrigPath); // -> 'test.js'
      console.log(file.revHash); // -> '4ad9f04399'

      // save bits & pieces
      var segs = file.revOrigPath.split('.');
      var extn = segs.slice(-1);
      var rest = segs.slice(0, segs.length - 1);

      // write the NEW path
      file.path = rest.concat('pre', file.revHash, 'sfx', extn).join('.');

      // send back to stream
      cb(null, file);
    }))
    .pipe(gulp.dest('dist'));
    //=> 'dist/test.pre.4ad9f04399.sfx.js'
});
```

That `modify` lib would have saved you some LOC & future headaches should your file sourcing change.

**Comment by atamas101** [comment]
@lukeed understood, and agreed: your example should work great, and it's very good (maybe consider adding this example to the docs somewhere, could help others too).
For my current use case, I need a way to append a ".cache" suffix to my revved files, so that my backend can handle requests differently. 
My main goal is to provide a simpler gulpfile.js, easy to read and understand for novices, and thus something like...
```js
gulp.task('version', function () {
  return gulp.src('src/test.js')
    .pipe(rev({hashSfx: '.sfx'}))
    .pipe(gulp.dest('dist'));
    //=> 'dist/test.4ad9f04399.sfx.js'
    .pipe(rev.manifest());
    .pipe(gulp.dest('dist'));
});
```
... would be better preffered.
Thank you again for all the time and help! 5* review ;)

**Comment by lukeed** [comment]
@atamas101 Thanks! :) 

And as mentioned, this could easily become your own plugin. Depending on how you set it up, others may find it useful too. It may end up looking something like:

```js
gulp.task('version', function () {
  return gulp.src('src/test.js')
    .pipe(rev())
    .pipe(revRename({
      glue: '.',
      prefix: 'pfx',
      suffix: 'sfx'
    }))
    .pipe(rev.manifest());
    .pipe(gulp.dest('dist'));
    //=> 'dist/test.pfx.HASH.sfx.js'
});
```

**Comment by atamas101** [comment]
@lukeed Yeah, I had already started on something like that :). 
Just finished: [@atamas101/gulp-rev-format](https://github.com/atamas101/gulp-rev-format)

Mine will be used like: 
```js
var gulp = require('gulp');
var rev = require('gulp-rev');
var revFormat = require('gulp-rev-format');

gulp.task('default', function () {
	return gulp.src('src/*.*')
		.pipe(rev())
		.pipe(revFormat({
            prefix: '-pfx-',
            suffix: '.sfx',
            lastExt: false
        }))
		.pipe(gulp.dest('dist'))
		.pipe(rev.manifest())
		.pipe(gulp.dest('dist'));

      //=> 'dist/test-pfx-HASH.sfx.js'
});
```
- feedback much appreciated

**Comment by bobthecow** [comment]
:+1: to everything here. Yay composing lots of small, focused plugins rather than making everything a mess of configuration!

**Comment by lukeed** [comment]
@bobthecow If I get around to it... I'll tag you in a future PR that removes all `manifest` behavior from this repo. I've seen you agree with that idea, perhaps more often than anyone else I've come across.

**Comment by bobthecow** [comment]
more than just "agree", i'm pretty sure i'm the one who suggested it originally 😄

**Comment by lukeed** [comment]
haha, fair enough 😜 Think I'm one of the last collaborators to enter the project; don't know the _full_ project history lol

**Comment by bobthecow** [comment]
@atamas101 feel free to send a PR adding `gulp-rev-format` to https://github.com/sindresorhus/gulp-rev#works-with-gulp-rev :)
