### ISSUE TITLE
Any idea where is the documentation for file.revHash ?

### ISSUE THREAD

**Issue by dreamerNcoder** [sindresorhus/gulp-rev#185]
Hi, 

I am trying to find an example related to file.revHash, and I am not able to get it. Please help me with the same. 
Thanks

**Comment by atamas101** [comment]
What exactly are you trying to do?

**Comment by bobthecow** [comment]
If you're just looking for an example of referencing it, `rev.manifest()` uses `file.revHash` to generate the manifest.

**Comment by benbieler** [comment]
Exactly! But since this type of question has come up a couple of times, I would advocate adding a more detailed documentation regarding this feature.

**Comment by dreamerNcoder** [comment]
yes, correct... I was trying to get the hash data and append the same in another js file. 
like: 
app.cache.js will be revised to app.asdas.cache.js
and I have a app.js file which look for file of type app.cache to get some data, 
So If I can get the file.revHash, then I can simply string replace the new app.cache with the app.asdas.cache in app.js

Hope I am making my problem clearer now..

**Comment by lukeed** [comment]
@dreamerNcoder Please have a look at [my comment](https://github.com/sindresorhus/gulp-rev/issues/186#issuecomment-229279896) over in #186. I linked some additional examples there too.

Let me know if that's what you were looking for.

**Comment by dreamerNcoder** [comment]
Thanks Lukeed... :+1:
