### ISSUE TITLE
Any idea where is the documentation for using transformer property ?

### ISSUE THREAD

**Issue by dreamerNcoder** [sindresorhus/gulp-rev#187]
Hi, 

I have noticed a behaviour that if I have app.test.js then the revision is done like app.asdas.test.js but I want it to be app.test.asdas.js. 

I went thorugh the documentation and found that transformer property has capabilities to do it..

Can some one help me with an example how to perform it ?

**Comment by lukeed** [comment]
This is the same question you've opened in #185.

**Comment by bobthecow** [comment]
The transformer has nothing to do with renaming the files. It's for parsing and serializing the manifest itself into a string. By default it uses `JSON.parse` / `JSON.stringify`, but you can supply anything else that implements `parse` and `stringify`, like YAML.
