### ISSUE TITLE
rev-manifest.json should exist before running Gulp

### ISSUE THREAD

**Issue by victorleal** [sindresorhus/gulp-rev#188]
### Description
When running Gulp for the first time, we don't have all those destination folders specified created. So Gulp will create them for us, and put the files inside them.
The problem is when the `rev-manifest.json` file will be filled. It doesn't exist (we are running Gulp for the very first time) and, even if we determine a place for it, Gulp (or gulp-rev, I couldn't see which one is responsible for creating the file) creates it **inside the project root folder**, instead of creating it inside the folder specified for it.

#### Steps to reproduce

1. Clean all of your `dest` folders. Be sure that you don't have a `rev-manifest.json` anywhere;
2. Run Gulp. Depending on your `gulpfile.js` some files will be copied, minified, and other tasks will be run. Be sure that you have a task to apply revisions to your files using `gulp-rev`;
3. The files will be versioned, but `rev-manifest.json` won't be in the specified folder. Instead, it will be in the project root.

Code of example:

```javascript
gulp.task('versionCSS', function() {
    return gulp
        .src(['css/theme.css'], { cwd: 'public', base: 'public' })
        .pipe(rev())
        .pipe(gulp.dest('public/build/css'))
        .pipe(rev.manifest( { base: 'public/build', cwd: 'public/build', merge: true } ))
        .pipe(gulp.dest('public/build'))
        .on('end', function() { gutil.log('CSS files versioned') });
});

```

**Comment by Jesseyx** [comment]
In this case, the manifest() need use "path" parameter.

**Comment by benbieler** [comment]
@victorleal I'll close this issue for now, but feel free to reopen.

**Comment by sasanazizi** [comment]
i have the same problem,
and i should run twice for update .html file with new hashed files urls when i have not a rev-manifest.json file priorly
