### ISSUE TITLE
Sourcemaps being piped further

### ISSUE THREAD

**Issue by mbrevda** [sindresorhus/gulp-rev#190]
### Description

In the following snippet, should sourcemaps be passed to the `fn` call on the last line? Until recently (about a 30-60 days ago) they weren't. Recently, my builds started failing. It's seems the reason is that `.map` files are passed in (and they don't include a `revOrigPath` property, causing `path()` to freak out, which is probably a whole different issue).

I'm trying to determine what changed: is there something that was added recently that would cause sourcemaps to be passed down the chain? Until recently, only the filename passes to `gulp.source` would show up there.

Thanks!
#### Steps to reproduce

``` js
            .pipe(rev())
            .pipe(gulpif(opts.ciBuild && !opts.prod, sourcemaps.write('./')))
            .pipe(gulp.dest(buildDir))
            .pipe(fn(function(file) {
```

**Comment by Zhouzi** [comment]
Hey @mbrevda! I'm going through the issues and wanted to know if you had a chance to figure this one out? Have you solved it and/or have some pointers to share? Thanks!

**Comment by mbrevda** [comment]
I don't know the answer. I no longer use this.

**Comment by Zhouzi** [comment]
Okay, thank you for sharing anyway! 👍
