### ISSUE TITLE
Previous hashed file is not replaced?

### ISSUE THREAD

**Issue by AakashGfude** [sindresorhus/gulp-rev#192]
### Hello everyone!

My gulp task is :  

```javascript
gulp.task('revision',function() {
   return gulp.src(['web/public/assets/javascript/*.js'])
    .pipe(rev())
    .pipe(gulp.dest('web/public/assets/javascript-build'))
    .pipe(rev.manifest())
    .pipe(gulp.dest('web/public/assets/javascript-build'))
})
```
But it does not replace the previously generated hash, instead it creates a new one. How would I replace the previously genereated one?

Thanks in advance.

**Comment by benbieler** [comment]
Hi, @AakashGfude,

If I understood your question correctly, [this](https://github.com/jamesknelson/gulp-rev-replace) might be that what you are looking for.

### Btw:
- When you create a ticket, please ALWAYS format your code, and give it the right coloring (I just did it for you, so remember next time ;) )

**Comment by AakashGfude** [comment]
Thanks. Will take care of the formatting. I am using gulp-rev-replace to rename or rewrite the names of the generated files in html pages, but what i was asking for is renaming the file created in the directory,i.e, the dest folder of rev itself. because at present it is creating copies of the same file with different hash names. 

The html files which contain the link and script tags are updating properly.

**Comment by lukeed** [comment]
File hashes are unique & based on their contents. If your file changes: new hash & new file.

Generally, people will clear (delete) a destination folder before building a new set of hashed, production assets. 

If this is not you, you may use [rev-del](https://github.com/callumacrae/rev-del).

**Comment by lukeed** [comment]
Closing, but feel free to continue here in case I/we missed anything :)

**Comment by AakashGfude** [comment]
Thanks for your help. gulp-del will do the trick.
