### ISSUE TITLE
Add support for SRI

### ISSUE THREAD

**Issue by kocsismate** [sindresorhus/gulp-rev#194]
Hey,

I have just read Troy Hunt's new article about SRI (https://www.troyhunt.com/protecting-your-embedded-content-with-subresource-integrity-sri/) and It would be fantastic if I could retrieve the SHA256, SHA384 or SHA512 of my assets from the manifest file.

I thought about modifying the JSON structure to something like this:

```json
{
  "jquery.js": {"name": "jquery-1234d2e3.js", "sha-256": "123456AE34ED21..."}
}
```

I am aware that is is a breaking change but i would be really curious about your opinion about this feature. Maybe you can come up with a better solution than me.

**Comment by bobthecow** [comment]
This would probably fit better (and be more gulpy) as its own `gulp-sri` plugin rather than an option to this plugin.

The one thing I'm not sure about is how to handle when multiple plugins want to get things into the rev manifest. I guess it's one more case for #184 to be a thing :)

**Comment by kocsismate** [comment]
Ok, thank you! Then I can only hope for soon-to-be interoperability with gulp-sri :)

**Comment by bobthecow** [comment]
If I were doing it, I'd add gulp-sri specific properties to files, the same way `rev*` properties are added, then in the hypothetical future rev manifest, make it gulp-sri property aware.

**Comment by bobthecow** [comment]
In that hypothetical future, it'd be great to have a kind of pluggable manifest thing that people could use to add other manifesty things… source maps? original paths?
