### ISSUE TITLE
Why not use full md5

### ISSUE THREAD

**Issue by milyord** [sindresorhus/gulp-rev#20]
Is there a particular reason why the md5 hash is sliced? Why not use the entire hash?

https://github.com/sindresorhus/gulp-rev/blob/master/index.js#L39

Thanks.

**Comment by mbrevda** [comment]
Here is an argument from another angle: **I like the look of a full hash**. It makes things look so sophisticated! 8 characters *seems* so flimsy, even if the science says otherwise. Can we at least specify the cut length? (I would want at least 16 chars, if not the full hash)

**Comment by sindresorhus** [comment]
Feel free to modify it, but we're not going to add options just because it looks better in your opinion. The more options the more useless things the user has to consider and care about. I prefer simple interfaces.
