### ISSUE TITLE
a better implements about manifest

### ISSUE THREAD

**Issue by WanderWang** [sindresorhus/gulp-rev#202]
why not use 

```
const originalFile = relPath(file.revOrigBase, file.revOrigPath);
```
instead of 
```
const originalFile = path.join(path.dirname(revisionedFile), path.basename(file.revOrigPath)).replace(/\\/g, '/');
```

on ```plugin.manifest``` method

**Comment by loveforgeter** [comment]
@WanderWang I think you code is right, current not support gulp-flatten

**Comment by sindresorhus** [comment]
Submit a [failing test](https://github.com/avajs/ava#failing-tests) of what's not working, and I'll take a look.

**Comment by Zhouzi** [comment]
@WanderWang @loveforgeter could you expand a bit on the issue you're facing? It'd be great if you could share the steps to reproduce the issue and the expected behaviour.
