### ISSUE TITLE
Option to disable sorting

### ISSUE THREAD

**Issue by inbeacon** [sindresorhus/gulp-rev#207]
Because js files need to be included into a specific order (like: jQuery first) the default sorting of the output is not very useful. (ie. makes this module useless or very cumbersome)  Can an option to disable sort be included?

**Comment by sindresorhus** [comment]
This module just creates a sorted manifest, that has no impact on the actual sorting in the stream. If you want to preserve that, see https://www.google.co.th/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=gulp+sort

**Comment by inbeacon** [comment]
It IS about sorting of the manifest. The manifest is used to generate a script header, using the order of the manifest. If the order gets sorted, we need to figure out the right sorting order using other methods, which is cumbersome.

I'm still using 2.0.1 as this version does not include the sorting, but this option would really be appreciated (and I saw others asking for this too, in another (closed) issue)
