### ISSUE TITLE
Produce only changed files

### ISSUE THREAD

**Issue by eldyvoon** [sindresorhus/gulp-rev#209]
I have bunch of files, below codes

```javascript
gulp.task('default', () =>
    // by default, gulp would pick `assets/css` as the base,
    // so we need to set it explicitly:
    gulp.src(['assets/css/*.css', 'assets/js/*.js'], {base: 'assets'})
        .pipe(gulp.dest('build/assets'))  // copy original assets to build dir
        .pipe(rev())
        .pipe(gulp.dest('build/assets'))  // write rev'd assets to build dir
        .pipe(rev.manifest())
        .pipe(gulp.dest('build/assets'))  // write manifest to build dir
);
```

which I took from the official example has a big problem. Users have to download unchanged files because the untouch files are added with new hash, why? How to solve this issue?

**Comment by bobthecow** [comment]
The hash is based on the content of the file. If the hash is different, the file content has changed. 

The most common reason I have seen for the file content changing when the source hasn't changed is if something non-deterministic is happening when building the assets, like `.pipe(concat())`.

**Comment by sindresorhus** [comment]
> non-deterministic is happening when building the assets, like .pipe(concat()).

It can be non-deterministic because the order in the gulp stream is not guaranteed, so the concatenated file in this case can be different even though the source files didn't change.

**Comment by Zhouzi** [comment]
@eldyvoon could you try to sort the streams with [gulp-sort](https://www.npmjs.com/package/gulp-sort) please? Here is what it should look like:

```javascript
gulp.task('default', () =>
    // by default, gulp would pick `assets/css` as the base,
    // so we need to set it explicitly:
    gulp.src(['assets/css/*.css', 'assets/js/*.js'], {base: 'assets'})
        .pipe(sort())
        .pipe(gulp.dest('build/assets'))  // copy original assets to build dir
        .pipe(rev())
        .pipe(gulp.dest('build/assets'))  // write rev'd assets to build dir
        .pipe(rev.manifest())
        .pipe(gulp.dest('build/assets'))  // write manifest to build dir
);
```

I personally don't think `gulp-rev` should sort streams by default as it is likely to have unexpected results (especially when relying on the order). We could add a note to the readme though.

What are your thoughts @sindresorhus @bobthecow?

**Comment by sindresorhus** [comment]
Out of scope for `gulp-rev`, but a note in the readme would be useful.

**Comment by bobthecow** [comment]
Agreed!

**Comment by lukeed** [comment]
Agreed. There's also [`gulp-changed`](https://github.com/sindresorhus/gulp-changed) if you need to filter down to newly-unique files only.
