### ISSUE TITLE
.json and .xml

### ISSUE THREAD

**Issue by weilinzung** [sindresorhus/gulp-rev#214]
I have image path inside of the .json and .xml, but when the use `rev`, then file name would changed but the content inside of the `.json`  and `.xml` would not update. Everything image path if inside of the `.js` would updated after the `rev` Any solutions? 

**manifest.json**

```json
{
 "name": "App",
 "icons": [
  {
   "src": "\/android-icon-36x36.png",
   "sizes": "36x36",
   "type": "image\/png",
   "density": "0.75"
  },
  {
   "src": "\/android-icon-48x48.png",
   "sizes": "48x48",
   "type": "image\/png",
   "density": "1.0"
  },
  {
   "src": "\/android-icon-72x72.png",
   "sizes": "72x72",
   "type": "image\/png",
   "density": "1.5"
  },
  {
   "src": "\/android-icon-96x96.png",
   "sizes": "96x96",
   "type": "image\/png",
   "density": "2.0"
  },
  {
   "src": "\/android-icon-144x144.png",
   "sizes": "144x144",
   "type": "image\/png",
   "density": "3.0"
  },
  {
   "src": "\/android-icon-192x192.png",
   "sizes": "192x192",
   "type": "image\/png",
   "density": "4.0"
  }
 ]
}
```

**Comment by Zhouzi** [comment]
The provided manifest.json is not the output of `gulp-rev` but the one used to declare your app's configuration.

Could you please:

1. Attach the code where you're using `gulp-rev`
2. Explain the expected result
3. Explain the current result

**Comment by weilinzung** [comment]
it is actual export with revision name `manifest-b58fcfa762.json`, only the image path inside of the json would not changed. if the `js` has image path, it would actual changed and everything works fine.

here is the code:

`
var rev = require('gulp-rev');
var replace = require('gulp-rev-replace');

gulp.task('revison', function () {
  return gulp.src('_site/**/*.json','_site/**/*.js')
  .pipe(rev())
  .pipe(replace())
  .pipe(gulp.dest('_site'))
});
`

**Comment by lukeed** [comment]
Your issue is actually with `gulp-rev-replace` because you're trying to update/_replace_ the new file names.

So if you go to that repo, you'll see [`options.replaceInExtensions `](https://github.com/jamesknelson/gulp-rev-replace#optionsreplaceinextensions).  By default, `.json` files are not included. So you need to update the array.

```js
var rev = require('gulp-rev');
var replace = require('gulp-rev-replace');

gulp.task('revison', function () {
  return gulp.src('_site/**/*.jpg','_site/**/*.png','_site/**/*.json','_site/**/*.js')
    .pipe(rev())
    .pipe(replace({
      replaceInExtensions: ['.js', '.css', '.html', '.hbs', '.json'] // <== here
    }))
    .pipe(gulp.dest('_site'))
});
```

Judging from your first post, you might want to add `.xml` to that array too.

**Comment by weilinzung** [comment]
Thanks Lukeed, but I don't think is working. it is still not updating the image name inside of the '.json' or '.xml'. Do you think `gulp-rev-replace` may not support these type files?

**Comment by lukeed** [comment]
@weilinzung Sorry, I don't actually use that plugin. But upon further inspection of the repo, you probably need to do this instead:

```js
gulp.task('revison', function () {
  return gulp.src('_site/**/*.jpg','_site/**/*.png','_site/**/*.json','_site/**/*.js')
    .pipe(rev())
    .pipe(gulp.dest('_site'))
    .pipe(rev.manifest())
    .pipe(gulp.dest('_site'))
});

gulp.task('revreplace', function () {
  var manifest = gulp.src('./_site/rev-manifest.json')

  return gulp.src('_site/**/*')
    .pipe(replace({
      manifest: manifest,
      replaceInExtensions: ['.js', '.css', '.html', '.hbs', '.json'] // <== here
    }))
    .pipe(gulp.dest('_site'))
});
```

Going to close this issue since it's a Usage question for `gulp-rev-replace`. Thanks!
