### ISSUE TITLE
Generates a new file hash remains the same

### ISSUE THREAD

**Issue by chenlong3** [sindresorhus/gulp-rev#215]
#### Steps to reproduce

    gulp.task('angular-min',function(){
    gulp.src(['./module/app.js','./module/_js/*.js','./module/*/service.js','./module/*/factory.js'])
        .pipe(ngAnnotate())
        .pipe(ngMin({dynamic:false}))
        .pipe(stripDebug())  //console
        .pipe(concat('my.min.js'))
        .pipe(rev())
        .pipe(uglify({outSourceMap:false,mangle:{except: ['$ocLazyLoad']}}))
        .pipe(gulp.dest('./dist'))
        .pipe(rev.manifest())                                   //- 生成一个rev-manifest.json
        .pipe(gulp.dest('./rev/js'));
});

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/gulp-rev#different-hash-for-unchanged-files
