### ISSUE TITLE
Hash cannot change when content is different

### ISSUE THREAD

**Issue by ttionya** [sindresorhus/gulp-rev#216]
## Description

I'm sure I have changed file content before use `gulp build`, but I don't know why the hash can't changed.

My code is here:

```js
gulp.task('md5-css', function () {
    return gulp.src('PublicDev/css/**')
        .pipe(minifyCss({ advanced: false }))
        .pipe(rev())
        .pipe(gulp.dest('Public/css'))
        .pipe(rev.manifest("css1.json"))
        .pipe(gulp.dest('./rev/css'));
});
```

And I use sourcetree, here is screenshot:

![image](https://cloud.githubusercontent.com/assets/22736919/26613005/14e91a64-45eb-11e7-94dd-431e2b6857fc.png)

It means different content with same hash.

My system is CentOS 6.9, NodeJS v7.10.0, gulp 3.9.1, gulp-rev 6.0.1

Thank you.

**Comment by Zhouzi** [comment]
Could you write the least code possible, reliably reproducing this, please?

**Comment by ttionya** [comment]
Sorry, it's my mistake.

Because Git think old file rename to new file, and `gulp-rev` work well.
