### ISSUE TITLE
rev.manifest() do not work in ubuntu

### ISSUE THREAD

**Issue by visgoods** [sindresorhus/gulp-rev#225]
#### Steps to reproduce
os:
Linux 85a2c3dbd9b0 4.9.36-moby #1 SMP Wed Jul 12 15:29:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 16.04.2 LTS \n \l

rev() do work , but rev.manifest()  can not run

**Comment by visgoods** [comment]
Ubuntu run in docker

**Comment by Zhouzi** [comment]
What do you mean by "it doesn't work"? Does it throw an error? Or the manifest is not generated? Or the manifest is corrupted?

Could you also share the code that makes it fail? And is the same setup working outside of docker?

**Comment by visgoods** [comment]
manifest is not generated and task job run over.
i have try gulp-rev version 7, likes ok

**Comment by Zhouzi** [comment]
So it's working fine with version 7 but is broken as of version 8? What version of NodeJS are you using?

Have a look at what changed between [v7.1.2...v8.0.0](https://github.com/sindresorhus/gulp-rev/compare/v7.1.2...v8.0.0). You probably need to make some changes on your side if you want to upgrade from 7 to 8.

**Comment by fmann** [comment]
I think we experienced this today too. Running on our local OS X dev boxes no issues running version 8.0.0, but on our production Ubuntu 16.04 server the manifest file did not get generated (though no error is thrown). Downgrading to 7.1.2 and it generates fine on all machines. 

Docker is not involved in either prod or dev environments.

Our current gulpfile is [here](https://github.com/PeaceGeeksSociety/services-advisor/blob/c49d4657a466c43717e2b7f9ec5eb7a3f098121d/gulpfile.js).

**Comment by Zhouzi** [comment]
Thanks @fmann, what version of NodeJS are you using in the Ubuntu instance?

**Comment by fmann** [comment]
@Zhouzi looks like we have node v4.2.6 and npm 5.3.0. We were at npm 3.5.2 at the start of this but upgraded while trying to debug this.

**Comment by Zhouzi** [comment]
And what version of NodeJS are you using on your local OSX?

**Comment by fmann** [comment]
My local has node v7.6.0 and npm 5.3.0.

**Comment by nulltone** [comment]
I'm having the same problem. I'm running on `node v4.4.3` and `npm 2.15.1` on Windows 10.

**Comment by ArtanisAce** [comment]
Same happening on RHEL 7.3, with node 4.2.3 and npm 3.10.8... seems like version 7.1.2 of gulp-rev works

**Comment by Zhouzi** [comment]
Just gave it a try with Node 4.2.3 and the error thrown is:

> this is not a typed array.

That's because `Buffer.from` has been introduced in Node v6.0.0. The fix is whether to update your Node version or stick with gulp-rev 7.1.2.

**Comment by danjohnso** [comment]
This is an issue in newer version of Node.  The newer overloads require an array, no overload for string.  Have to change Line 156 to new Buffer instead of Buffer.from
