### ISSUE TITLE
Change JSON key

### ISSUE THREAD

**Issue by beefchimi** [sindresorhus/gulp-rev#229]
I'm using this plugin to feed a `service-worker` manifest, where the asset file names never actually change, but I can request an update if the `hash` ends up being different.

Struggling to figure out how I can control the keys of my manifest. Basically, what I get by default will be:

`"file.js": "file-asdasdw.js"`

when what I really want is:

`"/assets/js/file.js": "asdasdw"`

Now, I have successfully figured out how to get just the `revHash` as the `value` by doing this:

```js
import gulp from 'gulp';
import rev from 'gulp-rev';
import through from 'through2';
import cacheManifest from '../cache-manifest';

function extractHash(file, enc, cb) {
  file.path = file.revHash;
  cb(null, file);
}

export function revision() {
  return gulp.src(cacheManifest)
    .pipe(rev())
    .pipe(through.obj(extractHash))
    .pipe(rev.manifest('./assets-manifest.json'))
    .pipe(gulp.dest('./'));
}
```

But I'm struggling with the key. For now, I've had to edit [this section](https://github.com/sindresorhus/gulp-rev/blob/master/index.js#L131-L134) of the source code to be:

```js
const trimmedPath = file.revOrigBase.replace(/^(.*?)\/dist/, '')
const revisionedFile = relPath(file.base, file.path);
const originalFile = path.join(path.dirname(revisionedFile), path.basename(file.revOrigPath)).replace(/\\/g, '/');
const newPath = trimmedPath + originalFile;

manifest[newPath] = file.revHash;
```

Working for now but I'd prefer not to be altering my dependencies :)

Any help would be greatly appreciated! Thanks!

**Comment by bobthecow** [comment]
Don't use `rev.manifest` at all. Just write the manifest directly instead of your `extractHash` stuff :)

**Comment by beefchimi** [comment]
Solved it by just using the `rev-hash` dep directly:

```js
import fs from 'fs';
import revHash from 'rev-hash';
import cacheManifest from '../../src/scripts/cache-manifest';

const assetsManifestPath = './assets-manifest.json';

export function revision() {
  return new Promise((resolve) => {
    const obj = {};

    cacheManifest.forEach((item) => {
      const key = item.replace('dist', '');
      obj[key] = revHash(fs.readFileSync(item));
    });

    resolve(obj);
  }).then((manifest) => {
    return fs.writeFileSync(assetsManifestPath, JSON.stringify(manifest, null, 2), 'utf-8');
  }).catch((error) => {
    return console.log(error); // eslint-disable-line no-console
  });
}
```
