### ISSUE TITLE
Garbage collector

### ISSUE THREAD

**Issue by AlexanderKozhevin** [sindresorhus/gulp-rev#232]
It would be cool if we had an options to leave only last 10 versions, or any other number.
I'm using it in production project and over the time it's generating a huge amount of versions. 
And I need to keep last 5 or 10 versions. But not others.

**Comment by Zhouzi** [comment]
While `gulp-rev` creates revisions, it doesn't take care of deleting the old ones. Please have a look at other [plugins working with `gulp-rev`](https://github.com/sindresorhus/gulp-rev#use-gulp-rev-in-combination-with-one-or-more-of), some are probably doing what you are looking for 😉

**Comment by bobthecow** [comment]
I believe https://github.com/shonny-ua/gulp-rev-outdated works with gulp-rev to do what you're looking for.
