### ISSUE TITLE
“gulp-rename-rev” is used by your main code. 

### ISSUE THREAD

**Issue by huanghui8030** [sindresorhus/gulp-rev#240]
### Description

On the basis of the plug-in, a specific rule of the plug-in, I do not know whether it can be used, I will give you a hello, if not, please let me know!

https://www.npmjs.com/package/gulp-rename-rev

**Comment by sindresorhus** [comment]
Sorry, I don't understand what you're saying.

**Comment by huanghui8030** [comment]
I uesd your main code to “gulp-rename-rev”, but I don't know whether I can user your main code.
