### ISSUE TITLE
Old revisions strategy

### ISSUE THREAD

**Issue by 0dp** [sindresorhus/gulp-rev#243]
### Description
I know that this package does not handle clean up of old revisions. But I've tried the recommend methods to no availability. So I would like to know what methods or strategies are being used by the users of this package.

I'm trying to implement the feature in UnderStrap, a WordPress theme hosted here on GitHub; if any one care to take a look?

**Comment by Zhouzi** [comment]
Could you elaborate on what you tried and what didn't work please?

**Comment by 0dp** [comment]
So I tried with `rev-del` expecting that new revisions are being made, the manifest file is then created/updated and old revision deleted from `./css` and `./js`
```
gulp.task( 'rev', function() {
  gulp.src([paths.css + '/theme.min.css', paths.js + '/theme.min.js'], {base: './'})
    .pipe(rev())
    .pipe(gulp.dest('./'))  
    .pipe(rev.manifest())
    .pipe(revDel({ dest: './' }))
    .pipe(gulp.dest('./'));  
});
```
and I've also tried gulp-rev-outdated
```
function cleaner() {
    return through.obj(function(file, enc, cb){
        rimraf( path.resolve( (file.cwd || process.cwd()), file.path), function (err) {
            if (err) {
                this.emit('error', new gutil.PluginError('Cleanup old files', err));
            }
            this.push(file);
            cb();
        }.bind(this));
    });
}


gulp.task('clean', function() {
    gulp.src( [paths.css + '/*.css'], {read: false})
        .pipe( revOutdated(1) ) // leave 1 latest asset file
        .pipe( cleaner() );
});
```

**Comment by 0dp** [comment]
@Zhouzi, any input on this? 😊

**Comment by Zhouzi** [comment]
@0dp Sorry, I was hoping to have some time to dig but I failed to do so. It'd be awesome if you could share a simple reproduction scenario (e.g a package.json and a gulpfile.js). It'd make it easier for me to investigate 😉

**Comment by 0dp** [comment]
Ahh no problem. feel free to download the project at: https://github.com/understrap/understrap 
Or if you prefer, I can make a smaller simplified version.
The important part is, if I install rev-del and include it in the gulp file, and include the above task. Old revisions are not deleted when the rev task is run.

**Comment by TheDancingCode** [comment]
Using [`gulp-rev-delete-original`](https://github.com/nib-health-funds/gulp-rev-delete-original) should to the trick.

Adapt your gulp task as follows:
```js
var revDel = require('gulp-rev-delete-original');

gulp.task( 'rev', function() {
  // by default, gulp would pick `assets/css` as the base,
  // so we need to set it explicitly:
  gulp.src([paths.css + '/theme.min.css', paths.js + '/theme.min.js'], {base: './'})
    .pipe(rev())
    .pipe(revDel())
    .pipe(gulp.dest('./'))  // write rev'd assets to build dir
    .pipe(rev.manifest())
    .pipe(gulp.dest('./'));  // write manifest to build dir
});
```

Hope that helps.

**Comment by 0dp** [comment]
Hi @TheDancingCode 
As you can see my original task takes theme.min.css and theme.min.js and makes revisions from them.
If you add revDel() after the revisions have been created, revDel will delete the original theme.min.css and theme.min.js.

This is not the desired effect I am after. 

I am only looking to be able to clean up old revisions not in use anymore by rev-manifest.json

**Comment by TheDancingCode** [comment]
@0dp 
Alright, I misunderstood. In that case, the task you wrote with `rev-del` works just fine over here.
```js
var revDel = require('rev-del');

gulp.task( 'rev', function() {
  // by default, gulp would pick `assets/css` as the base,
  // so we need to set it explicitly:
  gulp.src([paths.css + '/theme.min.css', paths.js + '/theme.min.js'], {base: './'})
    .pipe(rev())
    .pipe(gulp.dest('./'))  // write rev'd assets to build dir
    .pipe(rev.manifest())
    .pipe(revDel({dest: './'}))
    .pipe(gulp.dest('./'));  // write manifest to build dir
});
```

Probably needless to say, but as long as the contents of `theme.min.css` and `theme.min.js` stay the same, the revision hash will be the same, and so it will seem like the task doesn't do anything. Could that be what's going on?

**Comment by 0dp** [comment]
the rev task is in a sequence and only runs when theme.css/js is compiled, then minified to theme.min.css/js. So the flow is `compile changes to theme.css/js -> minify theme.css/js to theme.min.css/js -> make revisions of theme.min.css/js, write manifest file.

Could the reason why I can't get it to work be that the task is wrongly setup compared to folder tree?
```
.
├── css/                 # theme.min.css and its revisions live here 
├── js/                  # theme.min.js and its revisions live here 
└── rev-manifest.json
```

**Comment by TheDancingCode** [comment]
I'm puzzled, cause I cloned your repo and it really works just fine here. I make changes, the sequence runs and produces for example `theme-24e2eda284.min.css`. I make another change, the tasks run again, `theme-24e2eda284.min.css` is deleted and replaced by `theme-87fdda284f.min.css`.

**Comment by 0dp** [comment]
you mean in the rev-manifest.json right? Because that has never been the problem.
The problem is that eventually I will end up with 10's or 100's of garbage files in my css and js folder

**Comment by TheDancingCode** [comment]
No, I mean the actual files get replaced.

**Comment by 0dp** [comment]
This is so strange! Simply talking about it seems to have solved it. I definitely need to do more testing. Thanks a bunch @TheDancingCode

**Comment by Zhouzi** [comment]
Glad to hear things are sorted 👍
