### ISSUE TITLE
Some way to allow gulp-rev to play nicely with gulp-newer or gulp-changed

### ISSUE THREAD

**Issue by peterbraden** [sindresorhus/gulp-rev#32]
Revs break the filename mapping needed by plugins like gulp-newer or gulp-changed. Perhaps this is an issue for those plugins, but it seems like there should be a way to make them play nicely together.

**Comment by claydiffrient** [comment]
Are there any examples of using gulp-changed with gulp-rev since this change happened?

**Comment by tigranpetrossian** [comment]
+1, Would be great to see an example.
