### ISSUE TITLE
Always create rev-manifest.json even if no -rev

### ISSUE THREAD

**Issue by kud** [sindresorhus/gulp-rev#40]
Is it possible to create `rev-manifest.json` with: 

```
{
  "style.css": "style.css"
}
```

even if you don't want to rev your files?  It allows me in backend to always read `rev-manifest.json` and to include what I need/want from frontend.

**Comment by aslafy-z** [comment]
Here's a package that does that: https://github.com/aslafy-z/gulp-rev-fakemanifest
Built with code from here and original `gulp-rev-manifest`.

Here's a PR that does the same: https://github.com/lukeed/gulp-rev-manifest/pull/2.
