### ISSUE TITLE
Absolute paths are included when using multiple directory sources

### ISSUE THREAD

**Issue by c0** [sindresorhus/gulp-rev#48]
When using sources from multiple directories, the absolute path remains. I attempted to set `base` as an option to `gulp.src`, but that did not work either.

In this scenario, javascript is stored under `public/assets` and images in `public/images`. The manifest is stored in `public/assets/rev-manifest.json`.

I also attempted to fix it in #47, but the path to the asset remains.

Simple example:

```js
//gulpfile.js
var gulp       = require('gulp');
var rev        = require('gulp-rev');

var src = [
  'public/assets/*.js',
  'public/images/*.png',
];

var manifest = function () {
  gulp.src(src)
    .pipe(rev())
    .pipe(gulp.dest('public/assets'))
    .pipe(rev.manifest())
    .pipe(gulp.dest('public/assets'));
};

gulp.task('default', manifest);
```

```js
// public/assets/rev-manifest.json
{
  "foo.js": "foo-d41d8cd9.js",
  "foo.png": "/Users/full/path/to/public/assets/foo-d41d8cd9.png"
}
```

**Comment by sindresorhus** [comment]
Try out 3.0.0. Note the API has changed. See #77.
