### ISSUE TITLE
Absolute path in key of rev-manifest.json

### ISSUE THREAD

**Issue by codekirei** [sindresorhus/gulp-rev#54]
Similar issue to #48, but I think this is different enough to warrant a separate issue. Feel free to close if not.

When the following are true:
1. I don't copy an asset I want to `gulp-rev` to my destination dir before calling `rev()` on it
2. I generate `rev-manifest.json`
3. I explicitly set `base` to get a relative path in the value of `rev-manifest.json`

I end up with a `rev-manifest.json` that looks like this:

``` json
{
    "/super/long/absolute/path/scripts.js": "js/scripts-hash.js"
}
```

Simplified example of a gulp task to reproduce this:

``` javascript
var gulp = require('gulp');
var rev  = require('gulp-rev');

gulp.task('rev', function(){
  return gulp.src('source/js/scripts.js', {base: 'source'})
    .pipe(rev())
    .pipe(gulp.dest('dist'))
    .pipe(rev.manifest())
    .pipe(gulp.dest('dist'));
});
```

This puts `scripts.js` inside `dist/js/`, which is desirable for organization. It also includes `js/` in the value in `rev-manifest.json` to accurately reflect this. The problem is that absolute path in the key which makes consuming the manifest problematic.

Interestingly, I've found that interacting with the source before calling `rev()` avoids the long path. For example, mixing in the gulp-rename trick I mentioned in #53:

``` javascript
var gulp   = require('gulp');
var rev    = require('gulp-rev');
var rename = require('gulp-rename');

gulp.task('rev', function(){
  return gulp.src('source/js/scripts.js', {base: 'source'})
    .pipe(rename({extname: ''})
    .pipe(rev())
    .pipe(rename({extname: '.js'})
    .pipe(gulp.dest('dist'))
    .pipe(rev.manifest())
    .pipe(gulp.dest('dist'));
});
```

Suddenly, the absolute path is gone. `rev-manifest.json` looks like this:

``` json
{
    "js/scripts": "js/scripts-hash.js"
}
```

Any idea what's causing this interaction? I know I could get around this by copying the original file over to `/dist` by starting `gulp.task` with a `.pipe(gulp.dest('dist'))`, but I don't want the original file in `/dist`. I'd have to delete it later. Making a temporary copy of a file and deleting it later in the task doesn't seem very `gulp`-like.

Can anyone else reproduce based on the above, and if so, do you have any ideas why that absolute path is being generated? Is the cause in `gulp` itself or `gulp-rev`, or am I simply doing something wrong? I feel like there's probably a little detail I'm missing :sweat:

**Comment by rossthedevigner** [comment]
This was giving me issues as well and the workaround that I found (before finding this ticket) was to output the sources I wanted to rev() into a `./.tmp` directory, then output the rev'd files themselves into my `./dist`.

```
gulp.task('revision', ['build'], function() {
  return gulp.src([
      config.tmp + '/**/*',
      '!' + config.tmp + '/img/*norev*',
      '!' + config.tmp + '/img/*no-rev*'
    ])
    .pipe(rev())
    .pipe(gulp.dest(config.dest))
    .pipe(rev.manifest())
    .pipe(gulp.dest(config.dest))
});
```

That somehow kept the absolute/relative path key/value in the manifest.

You can also use `path.resolve(config.distDirectory)` instead of `path.join()`
