### ISSUE TITLE
Questions regarding the plugin

### ISSUE THREAD

**Issue by rthauby** [sindresorhus/gulp-rev#56]
1. When running concurrent tasks, much in the standard gulp flow, how does your plugin account for read/write locks when trying to access the manifest file? How are those multiple tasks reconciled so that they dont step on each other's toes?

I've tried it out and haven't seen a problem, but was still left wondering how it all "just worked".

2. I noticed that gulp-rev now supports creating a manifest file directly. Any idea what, if anything, they're doing differently to other plugins like gulp-rev-all?

**Comment by sindresorhus** [comment]
> When running concurrent tasks, much in the standard gulp flow, how does your plugin account for read/write locks when trying to access the manifest file?

I haven't tried, but we have a `merge` option in 3.0.0 which will merge with existing manifest, so it might work.

> I noticed that gulp-rev now supports creating a manifest file directly. Any idea what, if anything, they're doing differently to other plugins like gulp-rev-all?

https://github.com/smysnk/gulp-rev-all#why-fork
