### ISSUE TITLE
Can't append to rev-manifest.json

### ISSUE THREAD

**Issue by ijy** [sindresorhus/gulp-rev#65]
I've followed the guidelines but I'm unable to get a task to append to `rev-manifest.json` rather than replace it.

I run my css task first which generates the file hashes using gulp-rev and writes both the files and the manifest to disk in the `./dist/assets/` directory. All working correctly with the manifest generated. I then run my JS task and pass in the source `rev-manifest.json` file as the source:

```
.pipe(gulp.src('./dist/assets/rev-manifest.json')) // Pass in the current manifest so it's added to rather than replaced
```
Then run `rev.manifest()` and write to disk:

```
.pipe(rev()) // Hash the filenames
.pipe(gulp.dest('./dist/assets'))  // Write rev'd assets to build dir
.pipe(gulp.src('./dist/assets/rev-manifest.json')) // Pass in the current manifest so it's added to rather than replaced
.pipe(rev.manifest()) // Append hashed files to the current manifest
.pipe(gulp.dest('./dist/assets')) // Write manifest to build dir
```

Unfortunately the console returns an error however:

```
Finished 'js' after 39 ms

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^`
...
```

If I comment out the pipe where I pass in the source reference then it all works but overwrites the `rev-manifest.json` file losing the entries in their previously for my CSS files.

I'm using `"gulp-rev": "^1.1.0",`

Does anyone else have this problem or is there something I'm forgetting to do?

**Comment by fabiosussetto** [comment]
Got the same issue, tried the code from @jaypea PR and it seems to work, but if you have two tasks that you want to run in parallel (e.g. one to process js files and the other for css), it doesn't work as there's a race condition on whoever modify the manifest file first.

**Comment by bobthecow** [comment]
This should be fixed by #77 … do you mind trying it out?

```bash
npm install 'bobthecow/gulp-rev#all-the-pull-requests'
```

**Comment by sindresorhus** [comment]
Can someone confirm :arrow_double_up: fixes the issue?

**Comment by lollypopgr** [comment]
Problem remains for me even with @bobthecow patch

**Comment by sindresorhus** [comment]
See the `merge` option in 3.0.0.
