### ISSUE TITLE
scripts-50e8cdb8-50e8cdb8-50e8cdb8-50e8cdb8.js

### ISSUE THREAD

**Issue by ev45ive** [sindresorhus/gulp-rev#80]
gulp-rev with gulp-usemin seems to get in some kind of loop:

Error: ENAMETOOLONG, open '/home/mkulesza/projects/ipl-frontend/dist/styles/vendor-837c2ec4-837c2ec4-837c2ec4-837c2ec4-837c2ec4-837c2ec4-837c2ec4-837c2ec4-837c2ec4-837c2ec4-837c2ec4-837c2ec4-837c2ec4-837c2ec4-837c2ec4-837c2ec4-9c3d37ce-9c3d37ce-9c3d37ce-9c3d37ce-9c3d37ce-9c3d37ce-9c3d37ce-9c3d37ce-9c3d37ce-9c3d37ce-9c3d37ce-9c3d37ce-9c3d37ce-9c3d37ce-9c3d37ce-9c3d37ce.css'

```

gulp.task('usemin:dist', ['templates:dist','styles:dist'], function(){
    var js = [$.ngAnnotate(), $.rev()];
    var css = [
            // rewrite paths from source to compiled directories
            $.minifyCss(),
            // FIX paths in CSS - AFTER MINIFICATION ( gulp error )
            $.replace('/bower_components/sass-bootstrap/fonts/','/fonts/'),
            $.replace('images/images/','images/'),
            $.replace('app/images/','images/'),
            $.rev(),
        ];

    return gulp.src(['./app/index.html'])
        .pipe($.replace('<!-- #templates -->', '<script src="scripts/templates.min.js"></script>'))
        .pipe($.usemin({
            // there apparently cannot be two pipes (builds) with same name
            ie: [$.rev()],
            jsvendor: [$.rev()],
            js: js,
            templates: js,
            cssvendor: css,
            css: css
        }))
        .pipe(gulp.dest('dist'));
```

```

    <!-- build:jsvendor /scripts/vendor.js -->
    <!-- bower:js -->
    <script src="bower_components/jquery/jquery.js"></script>-
    <script src="bower_components/es5-shim/es5-shim.js"></script>
...
    <!-- endbuild -->
```

What might be the problem?
Why now each pipeline must have unique id? Previously it worked with multiple "build:js" for example.

**Comment by sindresorhus** [comment]
https://github.com/zont/gulp-usemin/issues/91

**Comment by greaterweb** [comment]
@sindresorhus, a shot in the dark, do you have any recommendations for a gulp-usemin replacement? I tracked down some of the issues with the plugin today but a fix doesn't look to be coming any time soon. A better solution is probably something closer to the grunt-usemin approach with the seperation of tasks, just don't know if anything like that is out there for gulp.
