### ISSUE TITLE
Rev'd file is written but the manifest isn't updated while watching

### ISSUE THREAD

**Issue by LarsFe** [sindresorhus/gulp-rev#81]
Hello,
I have a problem while running a watch-task. The following is my task to build images and their manifest:

```Javascript

assetLinkups = './app/config';

gulp.task('images', function(done) {
    runSequence('build-single-images', 'manifest-images', function() {
        return done();
    });
});

gulp.task('build-single-images', function() {
    var stream = gulp.src(appFiles.images)
        .pipe($.imagemin({ optimizationLevel: 7, progressive: true, interlaced: true }))
        .pipe(gulp.dest(paths.images.destTemp));

    return stream;
});

gulp.task('manifest-images', function() {
    var stream = gulp.src([paths.images.destTemp + '/**/*.{png,jpg,jpeg,gif,svg,ico}'])
        .pipe(rev())
        .pipe(gulp.dest(paths.images.dest))
        .pipe($.size({ showFiles: true }))
        .pipe(rev.manifest('assets-linkup-images.json'))
        .pipe(gulp.dest(assetLinkups));

    return stream;
});
```

And this is my watch-task:

```Javascript
gulp.task('watch', ['default'], function() {
    // watch images
    $.watch([ FILES TO WATCH FOR ])
        .pipe($.imagemin({ optimizationLevel: 7, progressive: true, interlaced: true }))
        .pipe(gulp.dest(paths.images.destTemp))
        .pipe(rev())
        .pipe(gulp.dest(paths.images.dest))
        .pipe($.size({ showFiles: true }))
        .pipe(rev.manifest('assets-linkup-images.json', { base: assetLinkups, merge: true }))
        .pipe(gulp.dest(assetLinkups));
});
```

So, when I start watching, first all images are built. After that I add a new image to a watched path. The image will be added and it gets a hash, but the key-value-pair isn't written to the manifest file.

Is there an error in the above code?

Greetings,
Lars

**Comment by bobthecow** [comment]
The issue you're having is that gulp-watch is a never ending stream, i.e. it never flushes. gulp-rev is (correctly) waiting for the stream to finish before writing the manifest file, and it just waits forever :)

You and #89 should get together, you've both got the same issue :)

**Comment by torifat** [comment]
@LarsFe It feels like your use case doesn't match with the goal of this plugin. Cache busting with watch doesn't make much sense to me. Can you please explain a bit? Why you need revision files inside watch (during development)?

**Comment by torifat** [comment]
@LarsFe Please reopen the issue if you want to discuss.

**Comment by LarsFe** [comment]
@torifat I work with Symfony and wrote short Twig Extensions to work with the generated json files.

```
{
    "base.css": "base-5fe67b05.css",
    ...
}
```
By using the extension in the various templates I get access to my hashed destination files.

```
{% block style %}
    <link href="{{ 'base.css' | css }}" type="text/css" rel="stylesheet"/>
{% endblock %}
```

Because I don't want to distinguish between dev and prod in Symfony while dealing with assets, I wrote it this way.

**Comment by LarsFe** [comment]
@bobthecow Also thanks for your answer. I must have overlooked your message. Sorry for my late comment. Time has past, I also saw the issue and various modifications were made. :)
