### ISSUE TITLE
Question: Removing original files / Handling source maps

### ISSUE THREAD

**Issue by gonsfx** [sindresorhus/gulp-rev#82]
I'm using gulp-rev to append content hashes to every file in my `dist` directory (except `.html` files).

Revving works fine on all files, including the sourcemaps that were generated into `dist` as `*.js.map` and `*.css.map` in the tasks `uglify` and `sass`.

Before deploying the `dist` directory to staging or production servers, i need to remove all original files - including the original, un-revved sourcemaps. The answer posted in #50 works for everything that is not a sourcemap.

 ```javascript
module.exports = function (gulp, config, $) {
	var dist = './dist';

	gulp.task('rev', [ 'sass', 'uglify', 'imagemin' ], function () {
		return gulp.src(dist + '/**/*.{js,css,jpg,png,svg}')
			.pipe($.sourcemaps.init({ loadMaps: true }))
			.pipe($.rev())
			.pipe($.sourcemaps.write('.'))
			.pipe(gulp.dest(dist))
			.pipe($.rev.manifest())
			.pipe(gulp.dest(dist));
	});
};
```

On a sidenote, this also generates a `name-hash.type.map` file for images - which is an undesired side-effect of my appoach to sourcemaps.

What would i have to do to rev all files in a directory (excluding `*.html`), keeping external sourcemaps working and removing all original files?

**Comment by gonsfx** [comment]
e.g. before running `rev` task:
```
/dist/index.html
/dist/js/app.js
/dist/js/app.js.map
/dist/css/app.css
/dist/css/app.css.map
/dist/img/logo.png
```

after running `rev` task:
```
/dist/index.html
/dist/rev-manifest.json
/dist/js/app-1cc05081.js
/dist/js/app-1cc05081.js.map
/dist/css/app-6d33a939.css
/dist/css/app-6d33a939.css.map
/dist/img/logo-b7d4e1b0.png
```

while keeping sourcemaps fully functional.

**Comment by bobthecow** [comment]
I don't know about the other, but you need to exclude images from your sourcemaps call… you could use gulp-filter or something for this, but probably the easiest way would be to create two streams and merge them:

```js
var es = require('event-stream');

module.exports = function (gulp, config, $) {
    var dist = './dist';

    gulp.task('rev', [ 'sass', 'uglify', 'imagemin' ], function () {
        var images = gulp.src(dist + '/**/*.{jpg,png,svg}')
            .pipe($.rev());

        var jsAndCss = gulp.src(dist + '/**/*.{js,css}')
            .pipe($.sourcemaps.init({ loadMaps: true }))
            .pipe($.rev())
            .pipe($.sourcemaps.write('.'))

        return es.merge(images, jsAndCss)
            .pipe(gulp.dest(dist))
            .pipe($.rev.manifest())
            .pipe(gulp.dest(dist));
    });
};
```

_(I didn't run this, but it should be pretty close)_

**Comment by gonsfx** [comment]
Awesome, thanks a lot!
That takes care of maps being generated for image files.

Whats left for me to find is a way to delete original files (including original sourcemaps, otherwise i could use the answer posted in #50).

**Comment by bobthecow** [comment]
Do you actually need to delete the original files? I typically leave them there.

**Comment by gonsfx** [comment]
I don't need to do so, but i want to. There's no point in keeping them and no point in deploying them somewhere. They can stay, but i'm not satisfied with it.

**Comment by gonsfx** [comment]
I solved it using `vinyl-paths` - not the most elegant solution, but it does what i want.
If someone knows a better way to get the desired result - feel free to educate me! :+1:

```javascript
var del = require('del');
var es = require('event-stream');
var vinylPaths = require('vinyl-paths');

module.exports = function (gulp, config, $) {
    var dist = './dist';

    gulp.task('rev', [ 'sass', 'uglify', 'imagemin' ], function (callback) {
        var image = vinylPaths();
        var source = vinylPaths();
        var map = vinylPaths();

        var imageStream = gulp.src(dist + '/**/*.{jpg,png,svg}')
            .pipe(image)
            .pipe($.rev());

        var sourceStream = gulp.src(dist + '/**/*.{js,css}')
            .pipe(source)
            .pipe($.sourcemaps.init({ loadMaps: true }))
            .pipe($.rev())
            .pipe($.sourcemaps.write('.'))

        gulp.src(dist + '/**/*.{map}').pipe(map);

        es.merge(imageStream, sourceStream)
            .pipe(gulp.dest(dist))
            .pipe($.rev.manifest())
            .pipe(gulp.dest(dist))
            .on('end', function () {
                del([].concat(image.paths, source.paths, map.paths), callback);
            });
    });
};
```
