### ISSUE TITLE
Oddly-named sourcemap files from gulp-ruby-sass

### ISSUE THREAD

**Issue by philgyford** [sindresorhus/gulp-rev#88]
I'm using gulp-ruby-sass to turn my SCSS files into a `site.css` file and a `site.css.map` file. Piping them through gulp-rev results in files like `site-2ca2ed30.css` and `site.css-ce8373b0.map`. Should the latter not be `site-ce8373b0.css.map`? ie, still have the `.css.map` extensions?

Here's my task:

    return gulp.src(paths.css.src+'site.scss')
        .pipe(sass({bundleExec: true, style: 'compressed'}))
        .pipe(rev())
        .pipe(gulp.dest(paths.css.dest))
        // Generate the manifest file that maps original to new filename.
        .pipe(rev.manifest())
        // Instead of saving it, parse the object in the file's content and save
        // it for later.
        .pipe(gutil.buffer(function(err, files){
            addToRevisions(JSON.parse(files[0].contents.toString()));
        }));

**Comment by bobthecow** [comment]
Yeah, that's weird and probably should be the other way around. This is a bit problematic without adding special cases for `*.*.map` and `*.min.*`, because a lot of other things (read: jQuery plugins) use dots in the "filename" part of the file, not just to separate extensions. Though you could make the case that those are far less common than min and map files, so maybe it would make more sense to do it the other way 'round?

@sindresorhus Thoughts?

**Comment by sindresorhus** [comment]
I've seen too many issues on grunt (which only considers the last part the extension) about this. So let's go with the extension being after the first dot.

**Comment by bobthecow** [comment]
:+1:

**Comment by callumacrae** [comment]
I'm getting slightly strange things happening with this module and sourcemaps. I'm calling `sourcemaps.write('./')` before I'm calling `rev()`, and I'm getting the following files output:

test.css + test-163f775a.css are identical:
```
body .div {
  color: blue; }

/*# sourceMappingURL=test.css.map */
```

Then test.css.map and test.css-6948376f.map are also identical:

```
{"version":3,"sources":["test.scss"],"names":[],"mappings":"AAGK;EAHG,aAIJ,EAAA","file":"test.css","sourcesContent":["$color: blue;\n\nbody {\n  .div {\n    color: $color;\n  }\n}\n"],"sourceRoot":"/source/"}
```

Shouldn't test.css and test.map be linked, and test-163f775a.css be linked to test.css-6948376f.map?

Let me know if you want me to open a new issue, but it seems related.
