### ISSUE TITLE
rev.forceWrite()

### ISSUE THREAD

**Issue by tjsail33** [sindresorhus/gulp-rev#89]
Thoughts on adding a rev.forceWrite() method to the plugin that can be used in a situation like gulp-watch (a never ending stream) to force the writing/merging of a manifest? This is useful in situations where rev is used to hash file names, but in development uses something you dont want to do a full 20 second compile when you only changed one file from the previous version.

**Comment by tjsail33** [comment]
@bobthecow any word on this? I can attempt to do it, however I lack experience with streams so I am not sure my solution would use all best practices.

**Comment by bobthecow** [comment]
I'm not sure what the best way to handle this is. It's kind of a weird flow to support, to be honest. Maybe your best bet would be to watch and trigger rev of _all_ files in a separate task, like [starting tasks on events](https://github.com/floatdrop/gulp-watch/blob/master/docs/readme.md#starting-tasks-on-events) in the gulp-watch docs?

**Comment by tjsail33** [comment]
So I gave this a go, and ALMOST had a functional version that would merge in real time, however the key path always ended up being the absolute path /Users/username/path/to/repo/assets/js/file.js instead of js/file.js. Thi obviously made the merge nonfunctional. I wasnt able to figure out why the code wasnt working, as i basically just copied and pasted the flush function into the transform function so the merge would be done in real time.

**Comment by torifat** [comment]
@tjsail33 It feels like your use case doesn't match with the goal of this plugin. Cache busting with watch doesn't make much sense to me. Can you please explain a bit? Why you need revision files inside watch (during development)?

**Comment by torifat** [comment]
@tjsail33 Please reopen the issue if you want to discuss.
