### ISSUE TITLE
Possible to get rev-ed resources other than images / fonts?

### ISSUE THREAD

**Issue by geekyme** [sindresorhus/gulp-rev#92]
Perhaps i have this piece of code which attempts to fetch a translation from the server. I want the translations to have a version so I can do some cache busting on it. 

```

function fetchLang(callback){
  return $.get('/api/translations/'+lang+'/');
}

```

Is it possible to dynamically change that source link ```$.get('/api/translations/'+lang+'/');``` to ```$.get('/api/translations/125712389312y/'+lang+'/');``` ?

**Comment by sindresorhus** [comment]
http://stackoverflow.com/questions/ask
