### ISSUE TITLE
Question: Is it possible to hash based only on the checksum of the file?

### ISSUE THREAD

**Issue by adjavaherian** [sindresorhus/gulp-rev#95]
I just deployed two clusters and had each one build and rev its own products before serving.  I'm getting a different hash for each product even though they are the same checksum.  So, I suspect that utime or random seeds are involved in computing the hash?  It doesn't look like you can specify how you want to compute the hash in the options.  Of course, one solution is to just build locally and check that into repo, but it might be cool to have this option.  Thoughts?

**Comment by bobthecow** [comment]
Nope. It's literally just an md5 of the file contents:

https://github.com/sindresorhus/gulp-rev/blob/master/index.js#L49

Are you concatenating files? If you're on a filesystem that doesn't guarantee directory order, they could be being concatenated in a different order?

**Comment by adjavaherian** [comment]
Thanks Bob, I just noticed that too.  Its just using MD5 from the crypto package.  I think you're right about the directory order.  They're on Ubuntu locally and CentOS remote.  Ubuntu is using ext4.  No worries, I should be building these products on Jenkins anyway, so there is only one source of truth.  Thanks.
