### ISSUE TITLE
Problems merging manifest

### ISSUE THREAD

**Issue by uberspeck** [sindresorhus/gulp-rev#99]
I'm not having any luck merging manifest files. No issues rev'ing them, but the manifest usually ends up only containing one key value pair. I've tried the suggestions made by @bobthecow [here](https://github.com/sindresorhus/gulp-rev/pull/77#issuecomment-68076646) but none of them seemed to work for me. I have a feeling my feeble grasp of the underpinnings of vinyl etc are the root of my frustrations, but I've been doing a fair amount of googling etc and nothing I try bears fruit.
```coffeescript
gulp.task("locales", ->
  locales = ["en-us","en-ca","fr-ca"]
  for locale in locales
    fileName = "#{locale}.json"
    gulp.src( "./src/**/#{locale}.json" )
      .pipe( $.concat( {path:fileName, cwd:"./"}, {newLine:","} ) )
      .pipe( $.wrap("{ <%= contents %> }", {}, {parse:false}) )
      .pipe( $.jsonminify() )
      .pipe( $.rev() )
      .pipe( gulp.dest( "./dist/locales" ) )
      .pipe( $.rev.manifest( path:"locales.json", merge:true ) )
      .pipe( gulp.dest( "./dist/rev" ) )
)
```
My goal is a directory of rev'd and concatenated locale files (one for each locale) and one corresponding manifest specific to the locales:
```
// /dist/locales/

en-ca-3be819c3.json
en-us-78b44b7b.json
fr-ca-2141dcef.json
```
```javascript
// /dist/rev/locales.json

{
    "en-ca.json": "en-ca-3be819c3.json",
    "en-us.json": "en-us-78b44b7b.json"
    "fr-ca.json": "fr-ca-2141dcef.json"
}
```
Currently, by locales.json file looks like this...
```javascript
// /dist/rev/locales.json

{
    "en-ca.json": "en-cs-3be819c3.json"
}
```

**Comment by floatdrop** [comment]
@uberspeck looks like you overwriting `locales.json` file in this for-loop. Try to split concatination+revisioning and manifest generation in different tasks.

**Comment by uberspeck** [comment]
Thanks for replying @floatdrop, I've tried several approaches to separating out the manifest generation and I'm getting nowhere. Seems my manifest file isn't even being generated...

```coffeescript
gulp.task( "concatLocales", ->
  locales = ["en-us","en-ca","fr-ca"]
  for locale in locales
    fileName = "#{locale}.json"
    gulp.src( "./src/**/#{locale}.json" )
      .pipe( $.concat( {path:fileName, cwd:"./"}, {newLine:","} ) )
      .pipe( $.wrap("{ <%= contents %> }", {}, {parse:false}) )
      .pipe( $.jsonminify() )
      .pipe( $.rev() )
      .pipe( gulp.dest( "./dist/locales" ) )
)

gulp.task( "createLocaleManifest", ->
  gulp.src( "./dist/locales/*.json" )
    .pipe( $.rev.manifest( base: "/dist/rev", path:"locales.json", merge:true ) )
    .pipe( gulp.dest( "dist/rev" ) )
)

gulp.task( "locales", ->
  $.runSequence( "concatLocales", "createLocaleManifest" )
)
```

**Comment by floatdrop** [comment]
@uberspeck you still missing the point - `for locale in locales` is synchronous operation, but `gulp.src` is not. What actually your code does - it runs pipeline 3 times (and `gulp.dest` is called again and again with same filename), instead of one.

Try this one:

```coffee
gulp.task( "concatLocales", ->
    gulp.src( "./src/**/{en-us,en-ca,fr-ca}.json" )
      .pipe( $.concat( {path:'concated-locales.json', cwd:"./"}, {newLine:","} ) )
      .pipe( $.wrap("{ <%= contents %> }", {}, {parse:false}) )
      .pipe( $.jsonminify() )
      .pipe( $.rev() )
      .pipe( gulp.dest( "./dist/locales" ) )
      .pipe( $.rev.manifest( base: "/dist/rev", path:"locales.json", merge:true ) )
      .pipe( gulp.dest( "dist/rev" ) )
)
```

**Comment by uberspeck** [comment]
Actually, i think the problem is I did a poor job of outlining my requirements :) Within my application there are many "modules" (it's an AngularJS app). Each module optionally has locale files so the directory structure looks something like this...
```
/src
    /users
        users-module.coffee
        users.scss
        en-us.json
        en-ca.json
        fr-ca.json
        ...
    /accounts
        accounts-module.coffee
        accounts.scss
        en-us.json
        en-ca.json
        fr-ca.json
        ...
```
This allows me to keep everything related to a given module in one place and adding/removing a module adds/removes *everything* associated with it. Since this app is kind of a monster so I don't want to concat all of my various languages into one big file. I only want to load the language that pertains the the users preferences and not waste bandwidth/time loading all of them. Given this, I first have to concat all ```/src/**/en-us.json``` files into one global ```/dist/locales/en-js.json``` file. *Then* I need to rev that global file and add it to the manifest. Of course I need to do this once for each language in order to keep the files separate.

So, my goal is to have the final outcome:
```
// /dist/locales/

en-ca-3be819c3.json
en-us-78b44b7b.json
fr-ca-2141dcef.json
```
```javascript
// /dist/rev/locales.json

{
    "en-ca.json": "en-ca-3be819c3.json",
    "en-us.json": "en-us-78b44b7b.json"
    "fr-ca.json": "fr-ca-2141dcef.json"
}
```
I hope that makes more sense? Sorry for the confusion!

**Comment by floatdrop** [comment]
@uberspeck can you create a repo with example (please in JavaScript)? I can look and fix it there.

**Comment by uberspeck** [comment]
Of course! I'll get that up ASAP!

**Comment by uberspeck** [comment]
[Here's a repo](https://github.com/uberspeck/rev-locale-test), thanks again for your assistance!

**Comment by floatdrop** [comment]
All sorted in https://github.com/uberspeck/rev-locale-test/pull/1

1. Never forget to use callback or return stream in gulp tasks (so it can properly order them)
2. `rev.manifest` must be after `rev`in pipeline (may be this should be in docs - but this is another issue).

**Comment by uberspeck** [comment]
Thanks @floatdrop! So i guess it's not possible to do this without rev'ing the files twice? :(

```
// /dist/rev/locales.json

{
  "en-ca-6ec37a0d.json": "en-ca-6ec37a0d-6ec37a0d.json",
  "en-us-1d154040.json": "en-us-1d154040-1d154040.json",
  "fr-CA-dab928ac.json": "fr-CA-dab928ac-dab928ac.json"
}
```

**Comment by floatdrop** [comment]
@uberspeck oops, I misslooked it. You can use https://github.com/floatdrop/save-stream to save vinyl-file objects from here https://github.com/uberspeck/rev-locale-test/pull/1/files#diff-b9e12334e9eafd8341a6107dd98510c9R65 and then pipe them in here https://github.com/uberspeck/rev-locale-test/pull/1/files#diff-b9e12334e9eafd8341a6107dd98510c9R79

This should work.

**Comment by floatdrop** [comment]
@uberspeck or just don't rev them here https://github.com/uberspeck/rev-locale-test/pull/1/files :dog:

**Comment by uberspeck** [comment]
Awesome, thx @floatdrop!
